// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: components/kubelet/action.proto

package kubelet

import (
	reflect "reflect"
	unsafe "unsafe"

	api "github.com/Azure/AKSFlexNode/components/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartKubeletService struct {
	state               protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata              `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *StartKubeletServiceSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *StartKubeletServiceStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartKubeletService) Reset() {
	*x = StartKubeletService{}
	mi := &file_components_kubelet_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKubeletService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKubeletService) ProtoMessage() {}

func (x *StartKubeletService) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartKubeletService) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *StartKubeletService) GetSpec() *StartKubeletServiceSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *StartKubeletService) GetStatus() *StartKubeletServiceStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *StartKubeletService) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *StartKubeletService) SetSpec(v *StartKubeletServiceSpec) {
	x.xxx_hidden_Spec = v
}

func (x *StartKubeletService) SetStatus(v *StartKubeletServiceStatus) {
	x.xxx_hidden_Status = v
}

func (x *StartKubeletService) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *StartKubeletService) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *StartKubeletService) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *StartKubeletService) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *StartKubeletService) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *StartKubeletService) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type StartKubeletService_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *StartKubeletServiceSpec
	Status   *StartKubeletServiceStatus
}

func (b0 StartKubeletService_builder) Build() *StartKubeletService {
	m0 := &StartKubeletService{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type KubeletArcCredential struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClusterResourceId *string                `protobuf:"bytes,1,opt,name=cluster_resource_id,json=clusterResourceId"`
	xxx_hidden_TenantId          *string                `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *KubeletArcCredential) Reset() {
	*x = KubeletArcCredential{}
	mi := &file_components_kubelet_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeletArcCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeletArcCredential) ProtoMessage() {}

func (x *KubeletArcCredential) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubeletArcCredential) GetClusterResourceId() string {
	if x != nil {
		if x.xxx_hidden_ClusterResourceId != nil {
			return *x.xxx_hidden_ClusterResourceId
		}
		return ""
	}
	return ""
}

func (x *KubeletArcCredential) GetTenantId() string {
	if x != nil {
		if x.xxx_hidden_TenantId != nil {
			return *x.xxx_hidden_TenantId
		}
		return ""
	}
	return ""
}

func (x *KubeletArcCredential) SetClusterResourceId(v string) {
	x.xxx_hidden_ClusterResourceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *KubeletArcCredential) SetTenantId(v string) {
	x.xxx_hidden_TenantId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *KubeletArcCredential) HasClusterResourceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KubeletArcCredential) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *KubeletArcCredential) ClearClusterResourceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ClusterResourceId = nil
}

func (x *KubeletArcCredential) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TenantId = nil
}

type KubeletArcCredential_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ClusterResourceId *string
	TenantId          *string
}

func (b0 KubeletArcCredential_builder) Build() *KubeletArcCredential {
	m0 := &KubeletArcCredential{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ClusterResourceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ClusterResourceId = b.ClusterResourceId
	}
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_TenantId = b.TenantId
	}
	return m0
}

type KubeletMSICredential struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId    *string                `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_ClientId    *string                `protobuf:"bytes,2,opt,name=client_id,json=clientId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *KubeletMSICredential) Reset() {
	*x = KubeletMSICredential{}
	mi := &file_components_kubelet_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeletMSICredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeletMSICredential) ProtoMessage() {}

func (x *KubeletMSICredential) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubeletMSICredential) GetTenantId() string {
	if x != nil {
		if x.xxx_hidden_TenantId != nil {
			return *x.xxx_hidden_TenantId
		}
		return ""
	}
	return ""
}

func (x *KubeletMSICredential) GetClientId() string {
	if x != nil {
		if x.xxx_hidden_ClientId != nil {
			return *x.xxx_hidden_ClientId
		}
		return ""
	}
	return ""
}

func (x *KubeletMSICredential) SetTenantId(v string) {
	x.xxx_hidden_TenantId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *KubeletMSICredential) SetClientId(v string) {
	x.xxx_hidden_ClientId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *KubeletMSICredential) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KubeletMSICredential) HasClientId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *KubeletMSICredential) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TenantId = nil
}

func (x *KubeletMSICredential) ClearClientId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClientId = nil
}

type KubeletMSICredential_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId *string
	ClientId *string
}

func (b0 KubeletMSICredential_builder) Build() *KubeletMSICredential {
	m0 := &KubeletMSICredential{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_TenantId = b.TenantId
	}
	if b.ClientId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ClientId = b.ClientId
	}
	return m0
}

type KubeletServicePrincipalCredential struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId     *string                `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_ClientId     *string                `protobuf:"bytes,2,opt,name=client_id,json=clientId"`
	xxx_hidden_ClientSecret *string                `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *KubeletServicePrincipalCredential) Reset() {
	*x = KubeletServicePrincipalCredential{}
	mi := &file_components_kubelet_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeletServicePrincipalCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeletServicePrincipalCredential) ProtoMessage() {}

func (x *KubeletServicePrincipalCredential) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubeletServicePrincipalCredential) GetTenantId() string {
	if x != nil {
		if x.xxx_hidden_TenantId != nil {
			return *x.xxx_hidden_TenantId
		}
		return ""
	}
	return ""
}

func (x *KubeletServicePrincipalCredential) GetClientId() string {
	if x != nil {
		if x.xxx_hidden_ClientId != nil {
			return *x.xxx_hidden_ClientId
		}
		return ""
	}
	return ""
}

func (x *KubeletServicePrincipalCredential) GetClientSecret() string {
	if x != nil {
		if x.xxx_hidden_ClientSecret != nil {
			return *x.xxx_hidden_ClientSecret
		}
		return ""
	}
	return ""
}

func (x *KubeletServicePrincipalCredential) SetTenantId(v string) {
	x.xxx_hidden_TenantId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *KubeletServicePrincipalCredential) SetClientId(v string) {
	x.xxx_hidden_ClientId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *KubeletServicePrincipalCredential) SetClientSecret(v string) {
	x.xxx_hidden_ClientSecret = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *KubeletServicePrincipalCredential) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KubeletServicePrincipalCredential) HasClientId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *KubeletServicePrincipalCredential) HasClientSecret() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *KubeletServicePrincipalCredential) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TenantId = nil
}

func (x *KubeletServicePrincipalCredential) ClearClientId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClientId = nil
}

func (x *KubeletServicePrincipalCredential) ClearClientSecret() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ClientSecret = nil
}

type KubeletServicePrincipalCredential_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId     *string
	ClientId     *string
	ClientSecret *string
}

func (b0 KubeletServicePrincipalCredential_builder) Build() *KubeletServicePrincipalCredential {
	m0 := &KubeletServicePrincipalCredential{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_TenantId = b.TenantId
	}
	if b.ClientId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ClientId = b.ClientId
	}
	if b.ClientSecret != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ClientSecret = b.ClientSecret
	}
	return m0
}

type KubeletBootstrapTokenCredential struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *KubeletBootstrapTokenCredential) Reset() {
	*x = KubeletBootstrapTokenCredential{}
	mi := &file_components_kubelet_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeletBootstrapTokenCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeletBootstrapTokenCredential) ProtoMessage() {}

func (x *KubeletBootstrapTokenCredential) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubeletBootstrapTokenCredential) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *KubeletBootstrapTokenCredential) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *KubeletBootstrapTokenCredential) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KubeletBootstrapTokenCredential) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

type KubeletBootstrapTokenCredential_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token *string
}

func (b0 KubeletBootstrapTokenCredential_builder) Build() *KubeletBootstrapTokenCredential {
	m0 := &KubeletBootstrapTokenCredential{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Token = b.Token
	}
	return m0
}

type ControlPlane struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Server                   *string                `protobuf:"bytes,1,opt,name=server"`
	xxx_hidden_CertificateAuthorityData []byte                 `protobuf:"bytes,2,opt,name=certificate_authority_data,json=certificateAuthorityData"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [1]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *ControlPlane) Reset() {
	*x = ControlPlane{}
	mi := &file_components_kubelet_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlane) ProtoMessage() {}

func (x *ControlPlane) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ControlPlane) GetServer() string {
	if x != nil {
		if x.xxx_hidden_Server != nil {
			return *x.xxx_hidden_Server
		}
		return ""
	}
	return ""
}

func (x *ControlPlane) GetCertificateAuthorityData() []byte {
	if x != nil {
		return x.xxx_hidden_CertificateAuthorityData
	}
	return nil
}

func (x *ControlPlane) SetServer(v string) {
	x.xxx_hidden_Server = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ControlPlane) SetCertificateAuthorityData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_CertificateAuthorityData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ControlPlane) HasServer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ControlPlane) HasCertificateAuthorityData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ControlPlane) ClearServer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Server = nil
}

func (x *ControlPlane) ClearCertificateAuthorityData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CertificateAuthorityData = nil
}

type ControlPlane_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Server                   *string
	CertificateAuthorityData []byte
}

func (b0 ControlPlane_builder) Build() *ControlPlane {
	m0 := &ControlPlane{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Server != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Server = b.Server
	}
	if b.CertificateAuthorityData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_CertificateAuthorityData = b.CertificateAuthorityData
	}
	return m0
}

type NodeAuthInfo struct {
	state               protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_AuthInfo isNodeAuthInfo_AuthInfo `protobuf_oneof:"auth_info"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NodeAuthInfo) Reset() {
	*x = NodeAuthInfo{}
	mi := &file_components_kubelet_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAuthInfo) ProtoMessage() {}

func (x *NodeAuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NodeAuthInfo) GetArcCredential() *KubeletArcCredential {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_ArcCredential); ok {
			return x.ArcCredential
		}
	}
	return nil
}

func (x *NodeAuthInfo) GetMsiCredential() *KubeletMSICredential {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_MsiCredential); ok {
			return x.MsiCredential
		}
	}
	return nil
}

func (x *NodeAuthInfo) GetServicePrincipalCredential() *KubeletServicePrincipalCredential {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_ServicePrincipalCredential); ok {
			return x.ServicePrincipalCredential
		}
	}
	return nil
}

func (x *NodeAuthInfo) GetBootstrapTokenCredential() *KubeletBootstrapTokenCredential {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_BootstrapTokenCredential); ok {
			return x.BootstrapTokenCredential
		}
	}
	return nil
}

func (x *NodeAuthInfo) SetArcCredential(v *KubeletArcCredential) {
	if v == nil {
		x.xxx_hidden_AuthInfo = nil
		return
	}
	x.xxx_hidden_AuthInfo = &nodeAuthInfo_ArcCredential{v}
}

func (x *NodeAuthInfo) SetMsiCredential(v *KubeletMSICredential) {
	if v == nil {
		x.xxx_hidden_AuthInfo = nil
		return
	}
	x.xxx_hidden_AuthInfo = &nodeAuthInfo_MsiCredential{v}
}

func (x *NodeAuthInfo) SetServicePrincipalCredential(v *KubeletServicePrincipalCredential) {
	if v == nil {
		x.xxx_hidden_AuthInfo = nil
		return
	}
	x.xxx_hidden_AuthInfo = &nodeAuthInfo_ServicePrincipalCredential{v}
}

func (x *NodeAuthInfo) SetBootstrapTokenCredential(v *KubeletBootstrapTokenCredential) {
	if v == nil {
		x.xxx_hidden_AuthInfo = nil
		return
	}
	x.xxx_hidden_AuthInfo = &nodeAuthInfo_BootstrapTokenCredential{v}
}

func (x *NodeAuthInfo) HasAuthInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AuthInfo != nil
}

func (x *NodeAuthInfo) HasArcCredential() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_ArcCredential)
	return ok
}

func (x *NodeAuthInfo) HasMsiCredential() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_MsiCredential)
	return ok
}

func (x *NodeAuthInfo) HasServicePrincipalCredential() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_ServicePrincipalCredential)
	return ok
}

func (x *NodeAuthInfo) HasBootstrapTokenCredential() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_BootstrapTokenCredential)
	return ok
}

func (x *NodeAuthInfo) ClearAuthInfo() {
	x.xxx_hidden_AuthInfo = nil
}

func (x *NodeAuthInfo) ClearArcCredential() {
	if _, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_ArcCredential); ok {
		x.xxx_hidden_AuthInfo = nil
	}
}

func (x *NodeAuthInfo) ClearMsiCredential() {
	if _, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_MsiCredential); ok {
		x.xxx_hidden_AuthInfo = nil
	}
}

func (x *NodeAuthInfo) ClearServicePrincipalCredential() {
	if _, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_ServicePrincipalCredential); ok {
		x.xxx_hidden_AuthInfo = nil
	}
}

func (x *NodeAuthInfo) ClearBootstrapTokenCredential() {
	if _, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_BootstrapTokenCredential); ok {
		x.xxx_hidden_AuthInfo = nil
	}
}

const NodeAuthInfo_AuthInfo_not_set_case case_NodeAuthInfo_AuthInfo = 0
const NodeAuthInfo_ArcCredential_case case_NodeAuthInfo_AuthInfo = 1
const NodeAuthInfo_MsiCredential_case case_NodeAuthInfo_AuthInfo = 2
const NodeAuthInfo_ServicePrincipalCredential_case case_NodeAuthInfo_AuthInfo = 3
const NodeAuthInfo_BootstrapTokenCredential_case case_NodeAuthInfo_AuthInfo = 4

func (x *NodeAuthInfo) WhichAuthInfo() case_NodeAuthInfo_AuthInfo {
	if x == nil {
		return NodeAuthInfo_AuthInfo_not_set_case
	}
	switch x.xxx_hidden_AuthInfo.(type) {
	case *nodeAuthInfo_ArcCredential:
		return NodeAuthInfo_ArcCredential_case
	case *nodeAuthInfo_MsiCredential:
		return NodeAuthInfo_MsiCredential_case
	case *nodeAuthInfo_ServicePrincipalCredential:
		return NodeAuthInfo_ServicePrincipalCredential_case
	case *nodeAuthInfo_BootstrapTokenCredential:
		return NodeAuthInfo_BootstrapTokenCredential_case
	default:
		return NodeAuthInfo_AuthInfo_not_set_case
	}
}

type NodeAuthInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_AuthInfo:
	ArcCredential              *KubeletArcCredential
	MsiCredential              *KubeletMSICredential
	ServicePrincipalCredential *KubeletServicePrincipalCredential
	BootstrapTokenCredential   *KubeletBootstrapTokenCredential
	// -- end of xxx_hidden_AuthInfo
}

func (b0 NodeAuthInfo_builder) Build() *NodeAuthInfo {
	m0 := &NodeAuthInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ArcCredential != nil {
		x.xxx_hidden_AuthInfo = &nodeAuthInfo_ArcCredential{b.ArcCredential}
	}
	if b.MsiCredential != nil {
		x.xxx_hidden_AuthInfo = &nodeAuthInfo_MsiCredential{b.MsiCredential}
	}
	if b.ServicePrincipalCredential != nil {
		x.xxx_hidden_AuthInfo = &nodeAuthInfo_ServicePrincipalCredential{b.ServicePrincipalCredential}
	}
	if b.BootstrapTokenCredential != nil {
		x.xxx_hidden_AuthInfo = &nodeAuthInfo_BootstrapTokenCredential{b.BootstrapTokenCredential}
	}
	return m0
}

type case_NodeAuthInfo_AuthInfo protoreflect.FieldNumber

func (x case_NodeAuthInfo_AuthInfo) String() string {
	md := file_components_kubelet_action_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isNodeAuthInfo_AuthInfo interface {
	isNodeAuthInfo_AuthInfo()
}

type nodeAuthInfo_ArcCredential struct {
	ArcCredential *KubeletArcCredential `protobuf:"bytes,1,opt,name=arc_credential,json=arcCredential,oneof"`
}

type nodeAuthInfo_MsiCredential struct {
	MsiCredential *KubeletMSICredential `protobuf:"bytes,2,opt,name=msi_credential,json=msiCredential,oneof"`
}

type nodeAuthInfo_ServicePrincipalCredential struct {
	ServicePrincipalCredential *KubeletServicePrincipalCredential `protobuf:"bytes,3,opt,name=service_principal_credential,json=servicePrincipalCredential,oneof"`
}

type nodeAuthInfo_BootstrapTokenCredential struct {
	BootstrapTokenCredential *KubeletBootstrapTokenCredential `protobuf:"bytes,4,opt,name=bootstrap_token_credential,json=bootstrapTokenCredential,oneof"`
}

func (*nodeAuthInfo_ArcCredential) isNodeAuthInfo_AuthInfo() {}

func (*nodeAuthInfo_MsiCredential) isNodeAuthInfo_AuthInfo() {}

func (*nodeAuthInfo_ServicePrincipalCredential) isNodeAuthInfo_AuthInfo() {}

func (*nodeAuthInfo_BootstrapTokenCredential) isNodeAuthInfo_AuthInfo() {}

// refs:
// https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
// https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
// https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
// TODO: consider importing kubelet config settings directly?
// We can use drop-in to override settings, but for now we follow the AgentBaker
// approach to declare these settings in CLI flag.
type KubeletConfig struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_KubeReserved         map[string]string      `protobuf:"bytes,1,rep,name=kube_reserved,json=kubeReserved" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_EvictionHard         map[string]string      `protobuf:"bytes,2,rep,name=eviction_hard,json=evictionHard" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Verbosity            int32                  `protobuf:"varint,3,opt,name=verbosity"`
	xxx_hidden_ImageGcHighThreshold int32                  `protobuf:"varint,4,opt,name=image_gc_high_threshold,json=imageGcHighThreshold"`
	xxx_hidden_ImageGcLowThreshold  int32                  `protobuf:"varint,5,opt,name=image_gc_low_threshold,json=imageGcLowThreshold"`
	xxx_hidden_ClusterDns           []string               `protobuf:"bytes,6,rep,name=cluster_dns,json=clusterDns"`
	xxx_hidden_MaxPods              int32                  `protobuf:"varint,7,opt,name=max_pods,json=maxPods"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *KubeletConfig) Reset() {
	*x = KubeletConfig{}
	mi := &file_components_kubelet_action_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeletConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeletConfig) ProtoMessage() {}

func (x *KubeletConfig) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubeletConfig) GetKubeReserved() map[string]string {
	if x != nil {
		return x.xxx_hidden_KubeReserved
	}
	return nil
}

func (x *KubeletConfig) GetEvictionHard() map[string]string {
	if x != nil {
		return x.xxx_hidden_EvictionHard
	}
	return nil
}

func (x *KubeletConfig) GetVerbosity() int32 {
	if x != nil {
		return x.xxx_hidden_Verbosity
	}
	return 0
}

func (x *KubeletConfig) GetImageGcHighThreshold() int32 {
	if x != nil {
		return x.xxx_hidden_ImageGcHighThreshold
	}
	return 0
}

func (x *KubeletConfig) GetImageGcLowThreshold() int32 {
	if x != nil {
		return x.xxx_hidden_ImageGcLowThreshold
	}
	return 0
}

func (x *KubeletConfig) GetClusterDns() []string {
	if x != nil {
		return x.xxx_hidden_ClusterDns
	}
	return nil
}

func (x *KubeletConfig) GetMaxPods() int32 {
	if x != nil {
		return x.xxx_hidden_MaxPods
	}
	return 0
}

func (x *KubeletConfig) SetKubeReserved(v map[string]string) {
	x.xxx_hidden_KubeReserved = v
}

func (x *KubeletConfig) SetEvictionHard(v map[string]string) {
	x.xxx_hidden_EvictionHard = v
}

func (x *KubeletConfig) SetVerbosity(v int32) {
	x.xxx_hidden_Verbosity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *KubeletConfig) SetImageGcHighThreshold(v int32) {
	x.xxx_hidden_ImageGcHighThreshold = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *KubeletConfig) SetImageGcLowThreshold(v int32) {
	x.xxx_hidden_ImageGcLowThreshold = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *KubeletConfig) SetClusterDns(v []string) {
	x.xxx_hidden_ClusterDns = v
}

func (x *KubeletConfig) SetMaxPods(v int32) {
	x.xxx_hidden_MaxPods = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *KubeletConfig) HasVerbosity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *KubeletConfig) HasImageGcHighThreshold() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *KubeletConfig) HasImageGcLowThreshold() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *KubeletConfig) HasMaxPods() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *KubeletConfig) ClearVerbosity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Verbosity = 0
}

func (x *KubeletConfig) ClearImageGcHighThreshold() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ImageGcHighThreshold = 0
}

func (x *KubeletConfig) ClearImageGcLowThreshold() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ImageGcLowThreshold = 0
}

func (x *KubeletConfig) ClearMaxPods() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_MaxPods = 0
}

type KubeletConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	KubeReserved         map[string]string
	EvictionHard         map[string]string
	Verbosity            *int32
	ImageGcHighThreshold *int32
	ImageGcLowThreshold  *int32
	ClusterDns           []string
	MaxPods              *int32
}

func (b0 KubeletConfig_builder) Build() *KubeletConfig {
	m0 := &KubeletConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_KubeReserved = b.KubeReserved
	x.xxx_hidden_EvictionHard = b.EvictionHard
	if b.Verbosity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Verbosity = *b.Verbosity
	}
	if b.ImageGcHighThreshold != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_ImageGcHighThreshold = *b.ImageGcHighThreshold
	}
	if b.ImageGcLowThreshold != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_ImageGcLowThreshold = *b.ImageGcLowThreshold
	}
	x.xxx_hidden_ClusterDns = b.ClusterDns
	if b.MaxPods != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_MaxPods = *b.MaxPods
	}
	return m0
}

type StartKubeletServiceSpec struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ControlPlane  *ControlPlane          `protobuf:"bytes,1,opt,name=control_plane,json=controlPlane"`
	xxx_hidden_NodeAuthInfo  *NodeAuthInfo          `protobuf:"bytes,2,opt,name=node_auth_info,json=nodeAuthInfo"`
	xxx_hidden_NodeLabels    map[string]string      `protobuf:"bytes,3,rep,name=node_labels,json=nodeLabels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_KubeletConfig *KubeletConfig         `protobuf:"bytes,4,opt,name=kubelet_config,json=kubeletConfig"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StartKubeletServiceSpec) Reset() {
	*x = StartKubeletServiceSpec{}
	mi := &file_components_kubelet_action_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKubeletServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKubeletServiceSpec) ProtoMessage() {}

func (x *StartKubeletServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartKubeletServiceSpec) GetControlPlane() *ControlPlane {
	if x != nil {
		return x.xxx_hidden_ControlPlane
	}
	return nil
}

func (x *StartKubeletServiceSpec) GetNodeAuthInfo() *NodeAuthInfo {
	if x != nil {
		return x.xxx_hidden_NodeAuthInfo
	}
	return nil
}

func (x *StartKubeletServiceSpec) GetNodeLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_NodeLabels
	}
	return nil
}

func (x *StartKubeletServiceSpec) GetKubeletConfig() *KubeletConfig {
	if x != nil {
		return x.xxx_hidden_KubeletConfig
	}
	return nil
}

func (x *StartKubeletServiceSpec) SetControlPlane(v *ControlPlane) {
	x.xxx_hidden_ControlPlane = v
}

func (x *StartKubeletServiceSpec) SetNodeAuthInfo(v *NodeAuthInfo) {
	x.xxx_hidden_NodeAuthInfo = v
}

func (x *StartKubeletServiceSpec) SetNodeLabels(v map[string]string) {
	x.xxx_hidden_NodeLabels = v
}

func (x *StartKubeletServiceSpec) SetKubeletConfig(v *KubeletConfig) {
	x.xxx_hidden_KubeletConfig = v
}

func (x *StartKubeletServiceSpec) HasControlPlane() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ControlPlane != nil
}

func (x *StartKubeletServiceSpec) HasNodeAuthInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NodeAuthInfo != nil
}

func (x *StartKubeletServiceSpec) HasKubeletConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_KubeletConfig != nil
}

func (x *StartKubeletServiceSpec) ClearControlPlane() {
	x.xxx_hidden_ControlPlane = nil
}

func (x *StartKubeletServiceSpec) ClearNodeAuthInfo() {
	x.xxx_hidden_NodeAuthInfo = nil
}

func (x *StartKubeletServiceSpec) ClearKubeletConfig() {
	x.xxx_hidden_KubeletConfig = nil
}

type StartKubeletServiceSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ControlPlane  *ControlPlane
	NodeAuthInfo  *NodeAuthInfo
	NodeLabels    map[string]string
	KubeletConfig *KubeletConfig
}

func (b0 StartKubeletServiceSpec_builder) Build() *StartKubeletServiceSpec {
	m0 := &StartKubeletServiceSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ControlPlane = b.ControlPlane
	x.xxx_hidden_NodeAuthInfo = b.NodeAuthInfo
	x.xxx_hidden_NodeLabels = b.NodeLabels
	x.xxx_hidden_KubeletConfig = b.KubeletConfig
	return m0
}

type StartKubeletServiceStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartKubeletServiceStatus) Reset() {
	*x = StartKubeletServiceStatus{}
	mi := &file_components_kubelet_action_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKubeletServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKubeletServiceStatus) ProtoMessage() {}

func (x *StartKubeletServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StartKubeletServiceStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StartKubeletServiceStatus_builder) Build() *StartKubeletServiceStatus {
	m0 := &StartKubeletServiceStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ResetKubelet struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *ResetKubeletSpec      `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *ResetKubeletStatus    `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResetKubelet) Reset() {
	*x = ResetKubelet{}
	mi := &file_components_kubelet_action_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetKubelet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetKubelet) ProtoMessage() {}

func (x *ResetKubelet) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResetKubelet) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ResetKubelet) GetSpec() *ResetKubeletSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *ResetKubelet) GetStatus() *ResetKubeletStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *ResetKubelet) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ResetKubelet) SetSpec(v *ResetKubeletSpec) {
	x.xxx_hidden_Spec = v
}

func (x *ResetKubelet) SetStatus(v *ResetKubeletStatus) {
	x.xxx_hidden_Status = v
}

func (x *ResetKubelet) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ResetKubelet) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *ResetKubelet) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *ResetKubelet) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *ResetKubelet) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *ResetKubelet) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type ResetKubelet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *ResetKubeletSpec
	Status   *ResetKubeletStatus
}

func (b0 ResetKubelet_builder) Build() *ResetKubelet {
	m0 := &ResetKubelet{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type ResetKubeletSpec struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetKubeletSpec) Reset() {
	*x = ResetKubeletSpec{}
	mi := &file_components_kubelet_action_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetKubeletSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetKubeletSpec) ProtoMessage() {}

func (x *ResetKubeletSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ResetKubeletSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ResetKubeletSpec_builder) Build() *ResetKubeletSpec {
	m0 := &ResetKubeletSpec{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ResetKubeletStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetKubeletStatus) Reset() {
	*x = ResetKubeletStatus{}
	mi := &file_components_kubelet_action_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetKubeletStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetKubeletStatus) ProtoMessage() {}

func (x *ResetKubeletStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubelet_action_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ResetKubeletStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ResetKubeletStatus_builder) Build() *ResetKubeletStatus {
	m0 := &ResetKubeletStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_components_kubelet_action_proto protoreflect.FileDescriptor

const file_components_kubelet_action_proto_rawDesc = "" +
	"\n" +
	"\x1fcomponents/kubelet/action.proto\x12\x1baks.flex.components.kubelet\x1a\x18components/api/api.proto\"\xee\x01\n" +
	"\x13StartKubeletService\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12H\n" +
	"\x04spec\x18\x02 \x01(\v24.aks.flex.components.kubelet.StartKubeletServiceSpecR\x04spec\x12N\n" +
	"\x06status\x18\x03 \x01(\v26.aks.flex.components.kubelet.StartKubeletServiceStatusR\x06status\"c\n" +
	"\x14KubeletArcCredential\x12.\n" +
	"\x13cluster_resource_id\x18\x01 \x01(\tR\x11clusterResourceId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"P\n" +
	"\x14KubeletMSICredential\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\x82\x01\n" +
	"!KubeletServicePrincipalCredential\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\"7\n" +
	"\x1fKubeletBootstrapTokenCredential\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"d\n" +
	"\fControlPlane\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12<\n" +
	"\x1acertificate_authority_data\x18\x02 \x01(\fR\x18certificateAuthorityData\"\xd6\x03\n" +
	"\fNodeAuthInfo\x12Z\n" +
	"\x0earc_credential\x18\x01 \x01(\v21.aks.flex.components.kubelet.KubeletArcCredentialH\x00R\rarcCredential\x12Z\n" +
	"\x0emsi_credential\x18\x02 \x01(\v21.aks.flex.components.kubelet.KubeletMSICredentialH\x00R\rmsiCredential\x12\x82\x01\n" +
	"\x1cservice_principal_credential\x18\x03 \x01(\v2>.aks.flex.components.kubelet.KubeletServicePrincipalCredentialH\x00R\x1aservicePrincipalCredential\x12|\n" +
	"\x1abootstrap_token_credential\x18\x04 \x01(\v2<.aks.flex.components.kubelet.KubeletBootstrapTokenCredentialH\x00R\x18bootstrapTokenCredentialB\v\n" +
	"\tauth_info\"\x9d\x04\n" +
	"\rKubeletConfig\x12a\n" +
	"\rkube_reserved\x18\x01 \x03(\v2<.aks.flex.components.kubelet.KubeletConfig.KubeReservedEntryR\fkubeReserved\x12a\n" +
	"\reviction_hard\x18\x02 \x03(\v2<.aks.flex.components.kubelet.KubeletConfig.EvictionHardEntryR\fevictionHard\x12\x1c\n" +
	"\tverbosity\x18\x03 \x01(\x05R\tverbosity\x125\n" +
	"\x17image_gc_high_threshold\x18\x04 \x01(\x05R\x14imageGcHighThreshold\x123\n" +
	"\x16image_gc_low_threshold\x18\x05 \x01(\x05R\x13imageGcLowThreshold\x12\x1f\n" +
	"\vcluster_dns\x18\x06 \x03(\tR\n" +
	"clusterDns\x12\x19\n" +
	"\bmax_pods\x18\a \x01(\x05R\amaxPods\x1a?\n" +
	"\x11KubeReservedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11EvictionHardEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x03\n" +
	"\x17StartKubeletServiceSpec\x12N\n" +
	"\rcontrol_plane\x18\x01 \x01(\v2).aks.flex.components.kubelet.ControlPlaneR\fcontrolPlane\x12O\n" +
	"\x0enode_auth_info\x18\x02 \x01(\v2).aks.flex.components.kubelet.NodeAuthInfoR\fnodeAuthInfo\x12e\n" +
	"\vnode_labels\x18\x03 \x03(\v2D.aks.flex.components.kubelet.StartKubeletServiceSpec.NodeLabelsEntryR\n" +
	"nodeLabels\x12Q\n" +
	"\x0ekubelet_config\x18\x04 \x01(\v2*.aks.flex.components.kubelet.KubeletConfigR\rkubeletConfig\x1a=\n" +
	"\x0fNodeLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1b\n" +
	"\x19StartKubeletServiceStatus\"\xd9\x01\n" +
	"\fResetKubelet\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12A\n" +
	"\x04spec\x18\x02 \x01(\v2-.aks.flex.components.kubelet.ResetKubeletSpecR\x04spec\x12G\n" +
	"\x06status\x18\x03 \x01(\v2/.aks.flex.components.kubelet.ResetKubeletStatusR\x06status\"\x12\n" +
	"\x10ResetKubeletSpec\"\x14\n" +
	"\x12ResetKubeletStatusB1Z/github.com/Azure/AKSFlexNode/components/kubeletb\beditionsp\xe9\a"

var file_components_kubelet_action_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_components_kubelet_action_proto_goTypes = []any{
	(*StartKubeletService)(nil),               // 0: aks.flex.components.kubelet.StartKubeletService
	(*KubeletArcCredential)(nil),              // 1: aks.flex.components.kubelet.KubeletArcCredential
	(*KubeletMSICredential)(nil),              // 2: aks.flex.components.kubelet.KubeletMSICredential
	(*KubeletServicePrincipalCredential)(nil), // 3: aks.flex.components.kubelet.KubeletServicePrincipalCredential
	(*KubeletBootstrapTokenCredential)(nil),   // 4: aks.flex.components.kubelet.KubeletBootstrapTokenCredential
	(*ControlPlane)(nil),                      // 5: aks.flex.components.kubelet.ControlPlane
	(*NodeAuthInfo)(nil),                      // 6: aks.flex.components.kubelet.NodeAuthInfo
	(*KubeletConfig)(nil),                     // 7: aks.flex.components.kubelet.KubeletConfig
	(*StartKubeletServiceSpec)(nil),           // 8: aks.flex.components.kubelet.StartKubeletServiceSpec
	(*StartKubeletServiceStatus)(nil),         // 9: aks.flex.components.kubelet.StartKubeletServiceStatus
	(*ResetKubelet)(nil),                      // 10: aks.flex.components.kubelet.ResetKubelet
	(*ResetKubeletSpec)(nil),                  // 11: aks.flex.components.kubelet.ResetKubeletSpec
	(*ResetKubeletStatus)(nil),                // 12: aks.flex.components.kubelet.ResetKubeletStatus
	nil,                                       // 13: aks.flex.components.kubelet.KubeletConfig.KubeReservedEntry
	nil,                                       // 14: aks.flex.components.kubelet.KubeletConfig.EvictionHardEntry
	nil,                                       // 15: aks.flex.components.kubelet.StartKubeletServiceSpec.NodeLabelsEntry
	(*api.Metadata)(nil),                      // 16: aks.flex.components.api.Metadata
}
var file_components_kubelet_action_proto_depIdxs = []int32{
	16, // 0: aks.flex.components.kubelet.StartKubeletService.metadata:type_name -> aks.flex.components.api.Metadata
	8,  // 1: aks.flex.components.kubelet.StartKubeletService.spec:type_name -> aks.flex.components.kubelet.StartKubeletServiceSpec
	9,  // 2: aks.flex.components.kubelet.StartKubeletService.status:type_name -> aks.flex.components.kubelet.StartKubeletServiceStatus
	1,  // 3: aks.flex.components.kubelet.NodeAuthInfo.arc_credential:type_name -> aks.flex.components.kubelet.KubeletArcCredential
	2,  // 4: aks.flex.components.kubelet.NodeAuthInfo.msi_credential:type_name -> aks.flex.components.kubelet.KubeletMSICredential
	3,  // 5: aks.flex.components.kubelet.NodeAuthInfo.service_principal_credential:type_name -> aks.flex.components.kubelet.KubeletServicePrincipalCredential
	4,  // 6: aks.flex.components.kubelet.NodeAuthInfo.bootstrap_token_credential:type_name -> aks.flex.components.kubelet.KubeletBootstrapTokenCredential
	13, // 7: aks.flex.components.kubelet.KubeletConfig.kube_reserved:type_name -> aks.flex.components.kubelet.KubeletConfig.KubeReservedEntry
	14, // 8: aks.flex.components.kubelet.KubeletConfig.eviction_hard:type_name -> aks.flex.components.kubelet.KubeletConfig.EvictionHardEntry
	5,  // 9: aks.flex.components.kubelet.StartKubeletServiceSpec.control_plane:type_name -> aks.flex.components.kubelet.ControlPlane
	6,  // 10: aks.flex.components.kubelet.StartKubeletServiceSpec.node_auth_info:type_name -> aks.flex.components.kubelet.NodeAuthInfo
	15, // 11: aks.flex.components.kubelet.StartKubeletServiceSpec.node_labels:type_name -> aks.flex.components.kubelet.StartKubeletServiceSpec.NodeLabelsEntry
	7,  // 12: aks.flex.components.kubelet.StartKubeletServiceSpec.kubelet_config:type_name -> aks.flex.components.kubelet.KubeletConfig
	16, // 13: aks.flex.components.kubelet.ResetKubelet.metadata:type_name -> aks.flex.components.api.Metadata
	11, // 14: aks.flex.components.kubelet.ResetKubelet.spec:type_name -> aks.flex.components.kubelet.ResetKubeletSpec
	12, // 15: aks.flex.components.kubelet.ResetKubelet.status:type_name -> aks.flex.components.kubelet.ResetKubeletStatus
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_components_kubelet_action_proto_init() }
func file_components_kubelet_action_proto_init() {
	if File_components_kubelet_action_proto != nil {
		return
	}
	file_components_kubelet_action_proto_msgTypes[6].OneofWrappers = []any{
		(*nodeAuthInfo_ArcCredential)(nil),
		(*nodeAuthInfo_MsiCredential)(nil),
		(*nodeAuthInfo_ServicePrincipalCredential)(nil),
		(*nodeAuthInfo_BootstrapTokenCredential)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_kubelet_action_proto_rawDesc), len(file_components_kubelet_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_kubelet_action_proto_goTypes,
		DependencyIndexes: file_components_kubelet_action_proto_depIdxs,
		MessageInfos:      file_components_kubelet_action_proto_msgTypes,
	}.Build()
	File_components_kubelet_action_proto = out.File
	file_components_kubelet_action_proto_goTypes = nil
	file_components_kubelet_action_proto_depIdxs = nil
}
