// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: components/services/actions/actions.proto

package actions

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyActionRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Item *anypb.Any             `protobuf:"bytes,1,opt,name=item"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyActionRequest) Reset() {
	*x = ApplyActionRequest{}
	mi := &file_components_services_actions_actions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyActionRequest) ProtoMessage() {}

func (x *ApplyActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_components_services_actions_actions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ApplyActionRequest) GetItem() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *ApplyActionRequest) SetItem(v *anypb.Any) {
	x.xxx_hidden_Item = v
}

func (x *ApplyActionRequest) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *ApplyActionRequest) ClearItem() {
	x.xxx_hidden_Item = nil
}

type ApplyActionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item *anypb.Any
}

func (b0 ApplyActionRequest_builder) Build() *ApplyActionRequest {
	m0 := &ApplyActionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	return m0
}

type ApplyActionResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Item *anypb.Any             `protobuf:"bytes,1,opt,name=item"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyActionResponse) Reset() {
	*x = ApplyActionResponse{}
	mi := &file_components_services_actions_actions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyActionResponse) ProtoMessage() {}

func (x *ApplyActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_components_services_actions_actions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ApplyActionResponse) GetItem() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *ApplyActionResponse) SetItem(v *anypb.Any) {
	x.xxx_hidden_Item = v
}

func (x *ApplyActionResponse) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *ApplyActionResponse) ClearItem() {
	x.xxx_hidden_Item = nil
}

type ApplyActionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item *anypb.Any
}

func (b0 ApplyActionResponse_builder) Build() *ApplyActionResponse {
	m0 := &ApplyActionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	return m0
}

var File_components_services_actions_actions_proto protoreflect.FileDescriptor

const file_components_services_actions_actions_proto_rawDesc = "" +
	"\n" +
	")components/services/actions/actions.proto\x12$aks.flex.components.services.actions\x1a\x19google/protobuf/any.proto\">\n" +
	"\x12ApplyActionRequest\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x04item\"?\n" +
	"\x13ApplyActionResponse\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x04item2\x97\x01\n" +
	"\x0eActionsService\x12\x84\x01\n" +
	"\vApplyAction\x128.aks.flex.components.services.actions.ApplyActionRequest\x1a9.aks.flex.components.services.actions.ApplyActionResponse\"\x00B:Z8github.com/Azure/AKSFlexNode/components/services/actionsb\beditionsp\xe9\a"

var file_components_services_actions_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_services_actions_actions_proto_goTypes = []any{
	(*ApplyActionRequest)(nil),  // 0: aks.flex.components.services.actions.ApplyActionRequest
	(*ApplyActionResponse)(nil), // 1: aks.flex.components.services.actions.ApplyActionResponse
	(*anypb.Any)(nil),           // 2: google.protobuf.Any
}
var file_components_services_actions_actions_proto_depIdxs = []int32{
	2, // 0: aks.flex.components.services.actions.ApplyActionRequest.item:type_name -> google.protobuf.Any
	2, // 1: aks.flex.components.services.actions.ApplyActionResponse.item:type_name -> google.protobuf.Any
	0, // 2: aks.flex.components.services.actions.ActionsService.ApplyAction:input_type -> aks.flex.components.services.actions.ApplyActionRequest
	1, // 3: aks.flex.components.services.actions.ActionsService.ApplyAction:output_type -> aks.flex.components.services.actions.ApplyActionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_components_services_actions_actions_proto_init() }
func file_components_services_actions_actions_proto_init() {
	if File_components_services_actions_actions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_services_actions_actions_proto_rawDesc), len(file_components_services_actions_actions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_components_services_actions_actions_proto_goTypes,
		DependencyIndexes: file_components_services_actions_actions_proto_depIdxs,
		MessageInfos:      file_components_services_actions_actions_proto_msgTypes,
	}.Build()
	File_components_services_actions_actions_proto = out.File
	file_components_services_actions_actions_proto_goTypes = nil
	file_components_services_actions_actions_proto_depIdxs = nil
}
