// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: components/linux/action.proto

package linux

import (
	reflect "reflect"
	unsafe "unsafe"

	api "github.com/Azure/AKSFlexNode/components/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureBaseOS struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *ConfigureBaseOSSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *ConfigureBaseOSStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigureBaseOS) Reset() {
	*x = ConfigureBaseOS{}
	mi := &file_components_linux_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureBaseOS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBaseOS) ProtoMessage() {}

func (x *ConfigureBaseOS) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigureBaseOS) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ConfigureBaseOS) GetSpec() *ConfigureBaseOSSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *ConfigureBaseOS) GetStatus() *ConfigureBaseOSStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *ConfigureBaseOS) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ConfigureBaseOS) SetSpec(v *ConfigureBaseOSSpec) {
	x.xxx_hidden_Spec = v
}

func (x *ConfigureBaseOS) SetStatus(v *ConfigureBaseOSStatus) {
	x.xxx_hidden_Status = v
}

func (x *ConfigureBaseOS) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ConfigureBaseOS) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *ConfigureBaseOS) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *ConfigureBaseOS) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *ConfigureBaseOS) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *ConfigureBaseOS) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type ConfigureBaseOS_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *ConfigureBaseOSSpec
	Status   *ConfigureBaseOSStatus
}

func (b0 ConfigureBaseOS_builder) Build() *ConfigureBaseOS {
	m0 := &ConfigureBaseOS{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type ConfigureBaseOSSpec struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureBaseOSSpec) Reset() {
	*x = ConfigureBaseOSSpec{}
	mi := &file_components_linux_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureBaseOSSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBaseOSSpec) ProtoMessage() {}

func (x *ConfigureBaseOSSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfigureBaseOSSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfigureBaseOSSpec_builder) Build() *ConfigureBaseOSSpec {
	m0 := &ConfigureBaseOSSpec{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConfigureBaseOSStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureBaseOSStatus) Reset() {
	*x = ConfigureBaseOSStatus{}
	mi := &file_components_linux_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureBaseOSStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBaseOSStatus) ProtoMessage() {}

func (x *ConfigureBaseOSStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfigureBaseOSStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfigureBaseOSStatus_builder) Build() *ConfigureBaseOSStatus {
	m0 := &ConfigureBaseOSStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DisableDocker struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *DisableDockerSpec     `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *DisableDockerStatus   `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DisableDocker) Reset() {
	*x = DisableDocker{}
	mi := &file_components_linux_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableDocker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableDocker) ProtoMessage() {}

func (x *DisableDocker) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DisableDocker) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *DisableDocker) GetSpec() *DisableDockerSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *DisableDocker) GetStatus() *DisableDockerStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *DisableDocker) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *DisableDocker) SetSpec(v *DisableDockerSpec) {
	x.xxx_hidden_Spec = v
}

func (x *DisableDocker) SetStatus(v *DisableDockerStatus) {
	x.xxx_hidden_Status = v
}

func (x *DisableDocker) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *DisableDocker) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *DisableDocker) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *DisableDocker) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *DisableDocker) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *DisableDocker) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type DisableDocker_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *DisableDockerSpec
	Status   *DisableDockerStatus
}

func (b0 DisableDocker_builder) Build() *DisableDocker {
	m0 := &DisableDocker{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type DisableDockerSpec struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableDockerSpec) Reset() {
	*x = DisableDockerSpec{}
	mi := &file_components_linux_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableDockerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableDockerSpec) ProtoMessage() {}

func (x *DisableDockerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DisableDockerSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DisableDockerSpec_builder) Build() *DisableDockerSpec {
	m0 := &DisableDockerSpec{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DisableDockerStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableDockerStatus) Reset() {
	*x = DisableDockerStatus{}
	mi := &file_components_linux_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableDockerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableDockerStatus) ProtoMessage() {}

func (x *DisableDockerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DisableDockerStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DisableDockerStatus_builder) Build() *DisableDockerStatus {
	m0 := &DisableDockerStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConfigureIPTables struct {
	state               protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata            `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *ConfigureIPTablesSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *ConfigureIPTablesStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigureIPTables) Reset() {
	*x = ConfigureIPTables{}
	mi := &file_components_linux_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureIPTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureIPTables) ProtoMessage() {}

func (x *ConfigureIPTables) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigureIPTables) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ConfigureIPTables) GetSpec() *ConfigureIPTablesSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *ConfigureIPTables) GetStatus() *ConfigureIPTablesStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *ConfigureIPTables) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ConfigureIPTables) SetSpec(v *ConfigureIPTablesSpec) {
	x.xxx_hidden_Spec = v
}

func (x *ConfigureIPTables) SetStatus(v *ConfigureIPTablesStatus) {
	x.xxx_hidden_Status = v
}

func (x *ConfigureIPTables) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ConfigureIPTables) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *ConfigureIPTables) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *ConfigureIPTables) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *ConfigureIPTables) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *ConfigureIPTables) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type ConfigureIPTables_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *ConfigureIPTablesSpec
	Status   *ConfigureIPTablesStatus
}

func (b0 ConfigureIPTables_builder) Build() *ConfigureIPTables {
	m0 := &ConfigureIPTables{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type ConfigureIPTablesSpec struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureIPTablesSpec) Reset() {
	*x = ConfigureIPTablesSpec{}
	mi := &file_components_linux_action_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureIPTablesSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureIPTablesSpec) ProtoMessage() {}

func (x *ConfigureIPTablesSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfigureIPTablesSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfigureIPTablesSpec_builder) Build() *ConfigureIPTablesSpec {
	m0 := &ConfigureIPTablesSpec{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConfigureIPTablesStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureIPTablesStatus) Reset() {
	*x = ConfigureIPTablesStatus{}
	mi := &file_components_linux_action_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureIPTablesStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureIPTablesStatus) ProtoMessage() {}

func (x *ConfigureIPTablesStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfigureIPTablesStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfigureIPTablesStatus_builder) Build() *ConfigureIPTablesStatus {
	m0 := &ConfigureIPTablesStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_components_linux_action_proto protoreflect.FileDescriptor

const file_components_linux_action_proto_rawDesc = "" +
	"\n" +
	"\x1dcomponents/linux/action.proto\x12\x19aks.flex.components.linux\x1a\x18components/api/api.proto\"\xde\x01\n" +
	"\x0fConfigureBaseOS\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12B\n" +
	"\x04spec\x18\x02 \x01(\v2..aks.flex.components.linux.ConfigureBaseOSSpecR\x04spec\x12H\n" +
	"\x06status\x18\x03 \x01(\v20.aks.flex.components.linux.ConfigureBaseOSStatusR\x06status\"\x15\n" +
	"\x13ConfigureBaseOSSpec\"\x17\n" +
	"\x15ConfigureBaseOSStatus\"\xd8\x01\n" +
	"\rDisableDocker\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12@\n" +
	"\x04spec\x18\x02 \x01(\v2,.aks.flex.components.linux.DisableDockerSpecR\x04spec\x12F\n" +
	"\x06status\x18\x03 \x01(\v2..aks.flex.components.linux.DisableDockerStatusR\x06status\"\x13\n" +
	"\x11DisableDockerSpec\"\x15\n" +
	"\x13DisableDockerStatus\"\xe4\x01\n" +
	"\x11ConfigureIPTables\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12D\n" +
	"\x04spec\x18\x02 \x01(\v20.aks.flex.components.linux.ConfigureIPTablesSpecR\x04spec\x12J\n" +
	"\x06status\x18\x03 \x01(\v22.aks.flex.components.linux.ConfigureIPTablesStatusR\x06status\"\x17\n" +
	"\x15ConfigureIPTablesSpec\"\x19\n" +
	"\x17ConfigureIPTablesStatusB/Z-github.com/Azure/AKSFlexNode/components/linuxb\beditionsp\xe9\a"

var file_components_linux_action_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_components_linux_action_proto_goTypes = []any{
	(*ConfigureBaseOS)(nil),         // 0: aks.flex.components.linux.ConfigureBaseOS
	(*ConfigureBaseOSSpec)(nil),     // 1: aks.flex.components.linux.ConfigureBaseOSSpec
	(*ConfigureBaseOSStatus)(nil),   // 2: aks.flex.components.linux.ConfigureBaseOSStatus
	(*DisableDocker)(nil),           // 3: aks.flex.components.linux.DisableDocker
	(*DisableDockerSpec)(nil),       // 4: aks.flex.components.linux.DisableDockerSpec
	(*DisableDockerStatus)(nil),     // 5: aks.flex.components.linux.DisableDockerStatus
	(*ConfigureIPTables)(nil),       // 6: aks.flex.components.linux.ConfigureIPTables
	(*ConfigureIPTablesSpec)(nil),   // 7: aks.flex.components.linux.ConfigureIPTablesSpec
	(*ConfigureIPTablesStatus)(nil), // 8: aks.flex.components.linux.ConfigureIPTablesStatus
	(*api.Metadata)(nil),            // 9: aks.flex.components.api.Metadata
}
var file_components_linux_action_proto_depIdxs = []int32{
	9, // 0: aks.flex.components.linux.ConfigureBaseOS.metadata:type_name -> aks.flex.components.api.Metadata
	1, // 1: aks.flex.components.linux.ConfigureBaseOS.spec:type_name -> aks.flex.components.linux.ConfigureBaseOSSpec
	2, // 2: aks.flex.components.linux.ConfigureBaseOS.status:type_name -> aks.flex.components.linux.ConfigureBaseOSStatus
	9, // 3: aks.flex.components.linux.DisableDocker.metadata:type_name -> aks.flex.components.api.Metadata
	4, // 4: aks.flex.components.linux.DisableDocker.spec:type_name -> aks.flex.components.linux.DisableDockerSpec
	5, // 5: aks.flex.components.linux.DisableDocker.status:type_name -> aks.flex.components.linux.DisableDockerStatus
	9, // 6: aks.flex.components.linux.ConfigureIPTables.metadata:type_name -> aks.flex.components.api.Metadata
	7, // 7: aks.flex.components.linux.ConfigureIPTables.spec:type_name -> aks.flex.components.linux.ConfigureIPTablesSpec
	8, // 8: aks.flex.components.linux.ConfigureIPTables.status:type_name -> aks.flex.components.linux.ConfigureIPTablesStatus
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_components_linux_action_proto_init() }
func file_components_linux_action_proto_init() {
	if File_components_linux_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_linux_action_proto_rawDesc), len(file_components_linux_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_linux_action_proto_goTypes,
		DependencyIndexes: file_components_linux_action_proto_depIdxs,
		MessageInfos:      file_components_linux_action_proto_msgTypes,
	}.Build()
	File_components_linux_action_proto = out.File
	file_components_linux_action_proto_goTypes = nil
	file_components_linux_action_proto_depIdxs = nil
}
