// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: components/kubeadm/action.proto

package kubeadm

import (
	api "github.com/Azure/AKSFlexNode/components/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KubeadmNodeJoin struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *KubeadmNodeJoinSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *KubeadmNodeJoinStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *KubeadmNodeJoin) Reset() {
	*x = KubeadmNodeJoin{}
	mi := &file_components_kubeadm_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeadmNodeJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeadmNodeJoin) ProtoMessage() {}

func (x *KubeadmNodeJoin) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubeadm_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubeadmNodeJoin) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *KubeadmNodeJoin) GetSpec() *KubeadmNodeJoinSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *KubeadmNodeJoin) GetStatus() *KubeadmNodeJoinStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *KubeadmNodeJoin) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *KubeadmNodeJoin) SetSpec(v *KubeadmNodeJoinSpec) {
	x.xxx_hidden_Spec = v
}

func (x *KubeadmNodeJoin) SetStatus(v *KubeadmNodeJoinStatus) {
	x.xxx_hidden_Status = v
}

func (x *KubeadmNodeJoin) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *KubeadmNodeJoin) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *KubeadmNodeJoin) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *KubeadmNodeJoin) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *KubeadmNodeJoin) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *KubeadmNodeJoin) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type KubeadmNodeJoin_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *KubeadmNodeJoinSpec
	Status   *KubeadmNodeJoinStatus
}

func (b0 KubeadmNodeJoin_builder) Build() *KubeadmNodeJoin {
	m0 := &KubeadmNodeJoin{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type ControlPlane struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Server                   *string                `protobuf:"bytes,1,opt,name=server"`
	xxx_hidden_CertificateAuthorityData []byte                 `protobuf:"bytes,2,opt,name=certificate_authority_data,json=certificateAuthorityData"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [1]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *ControlPlane) Reset() {
	*x = ControlPlane{}
	mi := &file_components_kubeadm_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlane) ProtoMessage() {}

func (x *ControlPlane) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubeadm_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ControlPlane) GetServer() string {
	if x != nil {
		if x.xxx_hidden_Server != nil {
			return *x.xxx_hidden_Server
		}
		return ""
	}
	return ""
}

func (x *ControlPlane) GetCertificateAuthorityData() []byte {
	if x != nil {
		return x.xxx_hidden_CertificateAuthorityData
	}
	return nil
}

func (x *ControlPlane) SetServer(v string) {
	x.xxx_hidden_Server = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ControlPlane) SetCertificateAuthorityData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_CertificateAuthorityData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ControlPlane) HasServer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ControlPlane) HasCertificateAuthorityData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ControlPlane) ClearServer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Server = nil
}

func (x *ControlPlane) ClearCertificateAuthorityData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CertificateAuthorityData = nil
}

type ControlPlane_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Server                   *string
	CertificateAuthorityData []byte
}

func (b0 ControlPlane_builder) Build() *ControlPlane {
	m0 := &ControlPlane{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Server != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Server = b.Server
	}
	if b.CertificateAuthorityData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_CertificateAuthorityData = b.CertificateAuthorityData
	}
	return m0
}

type Taint struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         *string                `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value       *string                `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Effect      *string                `protobuf:"bytes,3,opt,name=effect"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Taint) Reset() {
	*x = Taint{}
	mi := &file_components_kubeadm_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Taint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Taint) ProtoMessage() {}

func (x *Taint) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubeadm_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Taint) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *Taint) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *Taint) GetEffect() string {
	if x != nil {
		if x.xxx_hidden_Effect != nil {
			return *x.xxx_hidden_Effect
		}
		return ""
	}
	return ""
}

func (x *Taint) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Taint) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Taint) SetEffect(v string) {
	x.xxx_hidden_Effect = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Taint) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Taint) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Taint) HasEffect() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Taint) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = nil
}

func (x *Taint) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Value = nil
}

func (x *Taint) ClearEffect() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Effect = nil
}

type Taint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key    *string
	Value  *string
	Effect *string
}

func (b0 Taint_builder) Build() *Taint {
	m0 := &Taint{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Key = b.Key
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Value = b.Value
	}
	if b.Effect != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Effect = b.Effect
	}
	return m0
}

type Kubelet struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BootstrapAuthInfo  *NodeAuthInfo          `protobuf:"bytes,1,opt,name=bootstrap_auth_info,json=bootstrapAuthInfo"`
	xxx_hidden_NodeLabels         map[string]string      `protobuf:"bytes,2,rep,name=node_labels,json=nodeLabels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_NodeIp             *string                `protobuf:"bytes,3,opt,name=node_ip,json=nodeIp"`
	xxx_hidden_RegisterWithTaints *[]*Taint              `protobuf:"bytes,4,rep,name=register_with_taints,json=registerWithTaints"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Kubelet) Reset() {
	*x = Kubelet{}
	mi := &file_components_kubeadm_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kubelet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubelet) ProtoMessage() {}

func (x *Kubelet) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubeadm_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Kubelet) GetBootstrapAuthInfo() *NodeAuthInfo {
	if x != nil {
		return x.xxx_hidden_BootstrapAuthInfo
	}
	return nil
}

func (x *Kubelet) GetNodeLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_NodeLabels
	}
	return nil
}

func (x *Kubelet) GetNodeIp() string {
	if x != nil {
		if x.xxx_hidden_NodeIp != nil {
			return *x.xxx_hidden_NodeIp
		}
		return ""
	}
	return ""
}

func (x *Kubelet) GetRegisterWithTaints() []*Taint {
	if x != nil {
		if x.xxx_hidden_RegisterWithTaints != nil {
			return *x.xxx_hidden_RegisterWithTaints
		}
	}
	return nil
}

func (x *Kubelet) SetBootstrapAuthInfo(v *NodeAuthInfo) {
	x.xxx_hidden_BootstrapAuthInfo = v
}

func (x *Kubelet) SetNodeLabels(v map[string]string) {
	x.xxx_hidden_NodeLabels = v
}

func (x *Kubelet) SetNodeIp(v string) {
	x.xxx_hidden_NodeIp = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Kubelet) SetRegisterWithTaints(v []*Taint) {
	x.xxx_hidden_RegisterWithTaints = &v
}

func (x *Kubelet) HasBootstrapAuthInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BootstrapAuthInfo != nil
}

func (x *Kubelet) HasNodeIp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Kubelet) ClearBootstrapAuthInfo() {
	x.xxx_hidden_BootstrapAuthInfo = nil
}

func (x *Kubelet) ClearNodeIp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_NodeIp = nil
}

type Kubelet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BootstrapAuthInfo *NodeAuthInfo
	NodeLabels        map[string]string
	NodeIp            *string
	// List of taints to assign using the kubelet flag, in the format "key=value:effect"
	RegisterWithTaints []*Taint
}

func (b0 Kubelet_builder) Build() *Kubelet {
	m0 := &Kubelet{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BootstrapAuthInfo = b.BootstrapAuthInfo
	x.xxx_hidden_NodeLabels = b.NodeLabels
	if b.NodeIp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_NodeIp = b.NodeIp
	}
	x.xxx_hidden_RegisterWithTaints = &b.RegisterWithTaints
	return m0
}

type NodeAuthInfo struct {
	state               protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_AuthInfo isNodeAuthInfo_AuthInfo `protobuf_oneof:"auth_info"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NodeAuthInfo) Reset() {
	*x = NodeAuthInfo{}
	mi := &file_components_kubeadm_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAuthInfo) ProtoMessage() {}

func (x *NodeAuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubeadm_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NodeAuthInfo) GetToken() string {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *NodeAuthInfo) GetExec() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *NodeAuthInfo) SetToken(v string) {
	x.xxx_hidden_AuthInfo = &nodeAuthInfo_Token{v}
}

func (x *NodeAuthInfo) SetExec(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_AuthInfo = &nodeAuthInfo_Exec{v}
}

func (x *NodeAuthInfo) HasAuthInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AuthInfo != nil
}

func (x *NodeAuthInfo) HasToken() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_Token)
	return ok
}

func (x *NodeAuthInfo) HasExec() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_Exec)
	return ok
}

func (x *NodeAuthInfo) ClearAuthInfo() {
	x.xxx_hidden_AuthInfo = nil
}

func (x *NodeAuthInfo) ClearToken() {
	if _, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_Token); ok {
		x.xxx_hidden_AuthInfo = nil
	}
}

func (x *NodeAuthInfo) ClearExec() {
	if _, ok := x.xxx_hidden_AuthInfo.(*nodeAuthInfo_Exec); ok {
		x.xxx_hidden_AuthInfo = nil
	}
}

const NodeAuthInfo_AuthInfo_not_set_case case_NodeAuthInfo_AuthInfo = 0
const NodeAuthInfo_Token_case case_NodeAuthInfo_AuthInfo = 1
const NodeAuthInfo_Exec_case case_NodeAuthInfo_AuthInfo = 2

func (x *NodeAuthInfo) WhichAuthInfo() case_NodeAuthInfo_AuthInfo {
	if x == nil {
		return NodeAuthInfo_AuthInfo_not_set_case
	}
	switch x.xxx_hidden_AuthInfo.(type) {
	case *nodeAuthInfo_Token:
		return NodeAuthInfo_Token_case
	case *nodeAuthInfo_Exec:
		return NodeAuthInfo_Exec_case
	default:
		return NodeAuthInfo_AuthInfo_not_set_case
	}
}

type NodeAuthInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_AuthInfo:
	Token *string
	Exec  []byte
	// -- end of xxx_hidden_AuthInfo
}

func (b0 NodeAuthInfo_builder) Build() *NodeAuthInfo {
	m0 := &NodeAuthInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		x.xxx_hidden_AuthInfo = &nodeAuthInfo_Token{*b.Token}
	}
	if b.Exec != nil {
		x.xxx_hidden_AuthInfo = &nodeAuthInfo_Exec{b.Exec}
	}
	return m0
}

type case_NodeAuthInfo_AuthInfo protoreflect.FieldNumber

func (x case_NodeAuthInfo_AuthInfo) String() string {
	md := file_components_kubeadm_action_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isNodeAuthInfo_AuthInfo interface {
	isNodeAuthInfo_AuthInfo()
}

type nodeAuthInfo_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,oneof"`
}

type nodeAuthInfo_Exec struct {
	Exec []byte `protobuf:"bytes,2,opt,name=exec,oneof"`
}

func (*nodeAuthInfo_Token) isNodeAuthInfo_AuthInfo() {}

func (*nodeAuthInfo_Exec) isNodeAuthInfo_AuthInfo() {}

type KubeadmNodeJoinSpec struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ControlPlane *ControlPlane          `protobuf:"bytes,1,opt,name=control_plane,json=controlPlane"`
	xxx_hidden_Kubelet      *Kubelet               `protobuf:"bytes,2,opt,name=kubelet"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *KubeadmNodeJoinSpec) Reset() {
	*x = KubeadmNodeJoinSpec{}
	mi := &file_components_kubeadm_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeadmNodeJoinSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeadmNodeJoinSpec) ProtoMessage() {}

func (x *KubeadmNodeJoinSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubeadm_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubeadmNodeJoinSpec) GetControlPlane() *ControlPlane {
	if x != nil {
		return x.xxx_hidden_ControlPlane
	}
	return nil
}

func (x *KubeadmNodeJoinSpec) GetKubelet() *Kubelet {
	if x != nil {
		return x.xxx_hidden_Kubelet
	}
	return nil
}

func (x *KubeadmNodeJoinSpec) SetControlPlane(v *ControlPlane) {
	x.xxx_hidden_ControlPlane = v
}

func (x *KubeadmNodeJoinSpec) SetKubelet(v *Kubelet) {
	x.xxx_hidden_Kubelet = v
}

func (x *KubeadmNodeJoinSpec) HasControlPlane() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ControlPlane != nil
}

func (x *KubeadmNodeJoinSpec) HasKubelet() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kubelet != nil
}

func (x *KubeadmNodeJoinSpec) ClearControlPlane() {
	x.xxx_hidden_ControlPlane = nil
}

func (x *KubeadmNodeJoinSpec) ClearKubelet() {
	x.xxx_hidden_Kubelet = nil
}

type KubeadmNodeJoinSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ControlPlane *ControlPlane
	Kubelet      *Kubelet
}

func (b0 KubeadmNodeJoinSpec_builder) Build() *KubeadmNodeJoinSpec {
	m0 := &KubeadmNodeJoinSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ControlPlane = b.ControlPlane
	x.xxx_hidden_Kubelet = b.Kubelet
	return m0
}

type KubeadmNodeJoinStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeadmNodeJoinStatus) Reset() {
	*x = KubeadmNodeJoinStatus{}
	mi := &file_components_kubeadm_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeadmNodeJoinStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeadmNodeJoinStatus) ProtoMessage() {}

func (x *KubeadmNodeJoinStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubeadm_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type KubeadmNodeJoinStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 KubeadmNodeJoinStatus_builder) Build() *KubeadmNodeJoinStatus {
	m0 := &KubeadmNodeJoinStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_components_kubeadm_action_proto protoreflect.FileDescriptor

const file_components_kubeadm_action_proto_rawDesc = "" +
	"\n" +
	"\x1fcomponents/kubeadm/action.proto\x12\x1baks.flex.components.kubeadm\x1a\x18components/api/api.proto\"\xe2\x01\n" +
	"\x0fKubeadmNodeJoin\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12D\n" +
	"\x04spec\x18\x02 \x01(\v20.aks.flex.components.kubeadm.KubeadmNodeJoinSpecR\x04spec\x12J\n" +
	"\x06status\x18\x03 \x01(\v22.aks.flex.components.kubeadm.KubeadmNodeJoinStatusR\x06status\"d\n" +
	"\fControlPlane\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12<\n" +
	"\x1acertificate_authority_data\x18\x02 \x01(\fR\x18certificateAuthorityData\"G\n" +
	"\x05Taint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06effect\x18\x03 \x01(\tR\x06effect\"\xe9\x02\n" +
	"\aKubelet\x12Y\n" +
	"\x13bootstrap_auth_info\x18\x01 \x01(\v2).aks.flex.components.kubeadm.NodeAuthInfoR\x11bootstrapAuthInfo\x12U\n" +
	"\vnode_labels\x18\x02 \x03(\v24.aks.flex.components.kubeadm.Kubelet.NodeLabelsEntryR\n" +
	"nodeLabels\x12\x17\n" +
	"\anode_ip\x18\x03 \x01(\tR\x06nodeIp\x12T\n" +
	"\x14register_with_taints\x18\x04 \x03(\v2\".aks.flex.components.kubeadm.TaintR\x12registerWithTaints\x1a=\n" +
	"\x0fNodeLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\fNodeAuthInfo\x12\x16\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x12\x14\n" +
	"\x04exec\x18\x02 \x01(\fH\x00R\x04execB\v\n" +
	"\tauth_info\"\xa5\x01\n" +
	"\x13KubeadmNodeJoinSpec\x12N\n" +
	"\rcontrol_plane\x18\x01 \x01(\v2).aks.flex.components.kubeadm.ControlPlaneR\fcontrolPlane\x12>\n" +
	"\akubelet\x18\x02 \x01(\v2$.aks.flex.components.kubeadm.KubeletR\akubelet\"\x17\n" +
	"\x15KubeadmNodeJoinStatusB1Z/github.com/Azure/AKSFlexNode/components/kubeadmb\beditionsp\xe9\a"

var file_components_kubeadm_action_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_components_kubeadm_action_proto_goTypes = []any{
	(*KubeadmNodeJoin)(nil),       // 0: aks.flex.components.kubeadm.KubeadmNodeJoin
	(*ControlPlane)(nil),          // 1: aks.flex.components.kubeadm.ControlPlane
	(*Taint)(nil),                 // 2: aks.flex.components.kubeadm.Taint
	(*Kubelet)(nil),               // 3: aks.flex.components.kubeadm.Kubelet
	(*NodeAuthInfo)(nil),          // 4: aks.flex.components.kubeadm.NodeAuthInfo
	(*KubeadmNodeJoinSpec)(nil),   // 5: aks.flex.components.kubeadm.KubeadmNodeJoinSpec
	(*KubeadmNodeJoinStatus)(nil), // 6: aks.flex.components.kubeadm.KubeadmNodeJoinStatus
	nil,                           // 7: aks.flex.components.kubeadm.Kubelet.NodeLabelsEntry
	(*api.Metadata)(nil),          // 8: aks.flex.components.api.Metadata
}
var file_components_kubeadm_action_proto_depIdxs = []int32{
	8, // 0: aks.flex.components.kubeadm.KubeadmNodeJoin.metadata:type_name -> aks.flex.components.api.Metadata
	5, // 1: aks.flex.components.kubeadm.KubeadmNodeJoin.spec:type_name -> aks.flex.components.kubeadm.KubeadmNodeJoinSpec
	6, // 2: aks.flex.components.kubeadm.KubeadmNodeJoin.status:type_name -> aks.flex.components.kubeadm.KubeadmNodeJoinStatus
	4, // 3: aks.flex.components.kubeadm.Kubelet.bootstrap_auth_info:type_name -> aks.flex.components.kubeadm.NodeAuthInfo
	7, // 4: aks.flex.components.kubeadm.Kubelet.node_labels:type_name -> aks.flex.components.kubeadm.Kubelet.NodeLabelsEntry
	2, // 5: aks.flex.components.kubeadm.Kubelet.register_with_taints:type_name -> aks.flex.components.kubeadm.Taint
	1, // 6: aks.flex.components.kubeadm.KubeadmNodeJoinSpec.control_plane:type_name -> aks.flex.components.kubeadm.ControlPlane
	3, // 7: aks.flex.components.kubeadm.KubeadmNodeJoinSpec.kubelet:type_name -> aks.flex.components.kubeadm.Kubelet
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_components_kubeadm_action_proto_init() }
func file_components_kubeadm_action_proto_init() {
	if File_components_kubeadm_action_proto != nil {
		return
	}
	file_components_kubeadm_action_proto_msgTypes[4].OneofWrappers = []any{
		(*nodeAuthInfo_Token)(nil),
		(*nodeAuthInfo_Exec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_kubeadm_action_proto_rawDesc), len(file_components_kubeadm_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_kubeadm_action_proto_goTypes,
		DependencyIndexes: file_components_kubeadm_action_proto_depIdxs,
		MessageInfos:      file_components_kubeadm_action_proto_msgTypes,
	}.Build()
	File_components_kubeadm_action_proto = out.File
	file_components_kubeadm_action_proto_goTypes = nil
	file_components_kubeadm_action_proto_depIdxs = nil
}
