// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: components/arc/action.proto

package arc

import (
	api "github.com/Azure/AKSFlexNode/components/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallArc struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *InstallArcSpec        `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *InstallArcStatus      `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InstallArc) Reset() {
	*x = InstallArc{}
	mi := &file_components_arc_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallArc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallArc) ProtoMessage() {}

func (x *InstallArc) ProtoReflect() protoreflect.Message {
	mi := &file_components_arc_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstallArc) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *InstallArc) GetSpec() *InstallArcSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *InstallArc) GetStatus() *InstallArcStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *InstallArc) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *InstallArc) SetSpec(v *InstallArcSpec) {
	x.xxx_hidden_Spec = v
}

func (x *InstallArc) SetStatus(v *InstallArcStatus) {
	x.xxx_hidden_Status = v
}

func (x *InstallArc) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *InstallArc) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *InstallArc) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *InstallArc) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *InstallArc) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *InstallArc) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type InstallArc_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *InstallArcSpec
	Status   *InstallArcStatus
}

func (b0 InstallArc_builder) Build() *InstallArc {
	m0 := &InstallArc{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type InstallArcSpec struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SubscriptionId *string                `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId"`
	xxx_hidden_TenantId       *string                `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_ResourceGroup  *string                `protobuf:"bytes,3,opt,name=resource_group,json=resourceGroup"`
	xxx_hidden_Location       *string                `protobuf:"bytes,4,opt,name=location"`
	xxx_hidden_MachineName    *string                `protobuf:"bytes,5,opt,name=machine_name,json=machineName"`
	xxx_hidden_Tags           map[string]string      `protobuf:"bytes,6,rep,name=tags" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_AksClusterName *string                `protobuf:"bytes,7,opt,name=aks_cluster_name,json=aksClusterName"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *InstallArcSpec) Reset() {
	*x = InstallArcSpec{}
	mi := &file_components_arc_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallArcSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallArcSpec) ProtoMessage() {}

func (x *InstallArcSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_arc_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstallArcSpec) GetSubscriptionId() string {
	if x != nil {
		if x.xxx_hidden_SubscriptionId != nil {
			return *x.xxx_hidden_SubscriptionId
		}
		return ""
	}
	return ""
}

func (x *InstallArcSpec) GetTenantId() string {
	if x != nil {
		if x.xxx_hidden_TenantId != nil {
			return *x.xxx_hidden_TenantId
		}
		return ""
	}
	return ""
}

func (x *InstallArcSpec) GetResourceGroup() string {
	if x != nil {
		if x.xxx_hidden_ResourceGroup != nil {
			return *x.xxx_hidden_ResourceGroup
		}
		return ""
	}
	return ""
}

func (x *InstallArcSpec) GetLocation() string {
	if x != nil {
		if x.xxx_hidden_Location != nil {
			return *x.xxx_hidden_Location
		}
		return ""
	}
	return ""
}

func (x *InstallArcSpec) GetMachineName() string {
	if x != nil {
		if x.xxx_hidden_MachineName != nil {
			return *x.xxx_hidden_MachineName
		}
		return ""
	}
	return ""
}

func (x *InstallArcSpec) GetTags() map[string]string {
	if x != nil {
		return x.xxx_hidden_Tags
	}
	return nil
}

func (x *InstallArcSpec) GetAksClusterName() string {
	if x != nil {
		if x.xxx_hidden_AksClusterName != nil {
			return *x.xxx_hidden_AksClusterName
		}
		return ""
	}
	return ""
}

func (x *InstallArcSpec) SetSubscriptionId(v string) {
	x.xxx_hidden_SubscriptionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *InstallArcSpec) SetTenantId(v string) {
	x.xxx_hidden_TenantId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *InstallArcSpec) SetResourceGroup(v string) {
	x.xxx_hidden_ResourceGroup = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *InstallArcSpec) SetLocation(v string) {
	x.xxx_hidden_Location = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *InstallArcSpec) SetMachineName(v string) {
	x.xxx_hidden_MachineName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *InstallArcSpec) SetTags(v map[string]string) {
	x.xxx_hidden_Tags = v
}

func (x *InstallArcSpec) SetAksClusterName(v string) {
	x.xxx_hidden_AksClusterName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *InstallArcSpec) HasSubscriptionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InstallArcSpec) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InstallArcSpec) HasResourceGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *InstallArcSpec) HasLocation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *InstallArcSpec) HasMachineName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *InstallArcSpec) HasAksClusterName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *InstallArcSpec) ClearSubscriptionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SubscriptionId = nil
}

func (x *InstallArcSpec) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TenantId = nil
}

func (x *InstallArcSpec) ClearResourceGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ResourceGroup = nil
}

func (x *InstallArcSpec) ClearLocation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Location = nil
}

func (x *InstallArcSpec) ClearMachineName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_MachineName = nil
}

func (x *InstallArcSpec) ClearAksClusterName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_AksClusterName = nil
}

type InstallArcSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Azure subscription ID
	SubscriptionId *string
	// Azure tenant ID
	TenantId *string
	// Azure resource group for Arc machine
	ResourceGroup *string
	// Azure location for Arc machine
	Location *string
	// Arc machine name
	MachineName *string
	// Arc tags (key-value pairs)
	Tags map[string]string
	// Target AKS cluster name for RBAC assignments
	AksClusterName *string
}

func (b0 InstallArcSpec_builder) Build() *InstallArcSpec {
	m0 := &InstallArcSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SubscriptionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_SubscriptionId = b.SubscriptionId
	}
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_TenantId = b.TenantId
	}
	if b.ResourceGroup != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_ResourceGroup = b.ResourceGroup
	}
	if b.Location != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Location = b.Location
	}
	if b.MachineName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_MachineName = b.MachineName
	}
	x.xxx_hidden_Tags = b.Tags
	if b.AksClusterName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_AksClusterName = b.AksClusterName
	}
	return m0
}

type InstallArcStatus struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Phase             *string                `protobuf:"bytes,1,opt,name=phase"`
	xxx_hidden_Success           bool                   `protobuf:"varint,2,opt,name=success"`
	xxx_hidden_ErrorMessage      *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage"`
	xxx_hidden_MachineResourceId *string                `protobuf:"bytes,4,opt,name=machine_resource_id,json=machineResourceId"`
	xxx_hidden_PrincipalId       *string                `protobuf:"bytes,5,opt,name=principal_id,json=principalId"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *InstallArcStatus) Reset() {
	*x = InstallArcStatus{}
	mi := &file_components_arc_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallArcStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallArcStatus) ProtoMessage() {}

func (x *InstallArcStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_arc_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstallArcStatus) GetPhase() string {
	if x != nil {
		if x.xxx_hidden_Phase != nil {
			return *x.xxx_hidden_Phase
		}
		return ""
	}
	return ""
}

func (x *InstallArcStatus) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *InstallArcStatus) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *InstallArcStatus) GetMachineResourceId() string {
	if x != nil {
		if x.xxx_hidden_MachineResourceId != nil {
			return *x.xxx_hidden_MachineResourceId
		}
		return ""
	}
	return ""
}

func (x *InstallArcStatus) GetPrincipalId() string {
	if x != nil {
		if x.xxx_hidden_PrincipalId != nil {
			return *x.xxx_hidden_PrincipalId
		}
		return ""
	}
	return ""
}

func (x *InstallArcStatus) SetPhase(v string) {
	x.xxx_hidden_Phase = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *InstallArcStatus) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *InstallArcStatus) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *InstallArcStatus) SetMachineResourceId(v string) {
	x.xxx_hidden_MachineResourceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *InstallArcStatus) SetPrincipalId(v string) {
	x.xxx_hidden_PrincipalId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *InstallArcStatus) HasPhase() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InstallArcStatus) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InstallArcStatus) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *InstallArcStatus) HasMachineResourceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *InstallArcStatus) HasPrincipalId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *InstallArcStatus) ClearPhase() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Phase = nil
}

func (x *InstallArcStatus) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Success = false
}

func (x *InstallArcStatus) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ErrorMessage = nil
}

func (x *InstallArcStatus) ClearMachineResourceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MachineResourceId = nil
}

func (x *InstallArcStatus) ClearPrincipalId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PrincipalId = nil
}

type InstallArcStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Installation phase (validation, installation, registration, rbac, completed)
	Phase *string
	// Success status
	Success *bool
	// Error message if failed
	ErrorMessage *string
	// Arc machine resource ID once registered
	MachineResourceId *string
	// Managed identity principal ID
	PrincipalId *string
}

func (b0 InstallArcStatus_builder) Build() *InstallArcStatus {
	m0 := &InstallArcStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Phase != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Phase = b.Phase
	}
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Success = *b.Success
	}
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	if b.MachineResourceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_MachineResourceId = b.MachineResourceId
	}
	if b.PrincipalId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_PrincipalId = b.PrincipalId
	}
	return m0
}

var File_components_arc_action_proto protoreflect.FileDescriptor

const file_components_arc_action_proto_rawDesc = "" +
	"\n" +
	"\x1bcomponents/arc/action.proto\x12\x17aks.flex.components.arc\x1a\x18components/api/api.proto\"\xcb\x01\n" +
	"\n" +
	"InstallArc\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12;\n" +
	"\x04spec\x18\x02 \x01(\v2'.aks.flex.components.arc.InstallArcSpecR\x04spec\x12A\n" +
	"\x06status\x18\x03 \x01(\v2).aks.flex.components.arc.InstallArcStatusR\x06status\"\xe6\x02\n" +
	"\x0eInstallArcSpec\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12%\n" +
	"\x0eresource_group\x18\x03 \x01(\tR\rresourceGroup\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12!\n" +
	"\fmachine_name\x18\x05 \x01(\tR\vmachineName\x12E\n" +
	"\x04tags\x18\x06 \x03(\v21.aks.flex.components.arc.InstallArcSpec.TagsEntryR\x04tags\x12(\n" +
	"\x10aks_cluster_name\x18\a \x01(\tR\x0eaksClusterName\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x01\n" +
	"\x10InstallArcStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12.\n" +
	"\x13machine_resource_id\x18\x04 \x01(\tR\x11machineResourceId\x12!\n" +
	"\fprincipal_id\x18\x05 \x01(\tR\vprincipalIdB-Z+github.com/Azure/AKSFlexNode/components/arcb\beditionsp\xe9\a"

var file_components_arc_action_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_components_arc_action_proto_goTypes = []any{
	(*InstallArc)(nil),       // 0: aks.flex.components.arc.InstallArc
	(*InstallArcSpec)(nil),   // 1: aks.flex.components.arc.InstallArcSpec
	(*InstallArcStatus)(nil), // 2: aks.flex.components.arc.InstallArcStatus
	nil,                      // 3: aks.flex.components.arc.InstallArcSpec.TagsEntry
	(*api.Metadata)(nil),     // 4: aks.flex.components.api.Metadata
}
var file_components_arc_action_proto_depIdxs = []int32{
	4, // 0: aks.flex.components.arc.InstallArc.metadata:type_name -> aks.flex.components.api.Metadata
	1, // 1: aks.flex.components.arc.InstallArc.spec:type_name -> aks.flex.components.arc.InstallArcSpec
	2, // 2: aks.flex.components.arc.InstallArc.status:type_name -> aks.flex.components.arc.InstallArcStatus
	3, // 3: aks.flex.components.arc.InstallArcSpec.tags:type_name -> aks.flex.components.arc.InstallArcSpec.TagsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_components_arc_action_proto_init() }
func file_components_arc_action_proto_init() {
	if File_components_arc_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_arc_action_proto_rawDesc), len(file_components_arc_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_arc_action_proto_goTypes,
		DependencyIndexes: file_components_arc_action_proto_depIdxs,
		MessageInfos:      file_components_arc_action_proto_msgTypes,
	}.Build()
	File_components_arc_action_proto = out.File
	file_components_arc_action_proto_goTypes = nil
	file_components_arc_action_proto_depIdxs = nil
}
