// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: components/cri/action.proto

package cri

import (
	reflect "reflect"
	unsafe "unsafe"

	api "github.com/Azure/AKSFlexNode/components/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadCRIBinaries struct {
	state               protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata              `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *DownloadCRIBinariesSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *DownloadCRIBinariesStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DownloadCRIBinaries) Reset() {
	*x = DownloadCRIBinaries{}
	mi := &file_components_cri_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadCRIBinaries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadCRIBinaries) ProtoMessage() {}

func (x *DownloadCRIBinaries) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadCRIBinaries) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *DownloadCRIBinaries) GetSpec() *DownloadCRIBinariesSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *DownloadCRIBinaries) GetStatus() *DownloadCRIBinariesStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *DownloadCRIBinaries) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *DownloadCRIBinaries) SetSpec(v *DownloadCRIBinariesSpec) {
	x.xxx_hidden_Spec = v
}

func (x *DownloadCRIBinaries) SetStatus(v *DownloadCRIBinariesStatus) {
	x.xxx_hidden_Status = v
}

func (x *DownloadCRIBinaries) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *DownloadCRIBinaries) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *DownloadCRIBinaries) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *DownloadCRIBinaries) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *DownloadCRIBinaries) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *DownloadCRIBinaries) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type DownloadCRIBinaries_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *DownloadCRIBinariesSpec
	Status   *DownloadCRIBinariesStatus
}

func (b0 DownloadCRIBinaries_builder) Build() *DownloadCRIBinaries {
	m0 := &DownloadCRIBinaries{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type DownloadCRIBinariesSpec struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerdVersion *string                `protobuf:"bytes,1,opt,name=containerd_version,json=containerdVersion"`
	xxx_hidden_RuncVersion       *string                `protobuf:"bytes,2,opt,name=runc_version,json=runcVersion"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DownloadCRIBinariesSpec) Reset() {
	*x = DownloadCRIBinariesSpec{}
	mi := &file_components_cri_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadCRIBinariesSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadCRIBinariesSpec) ProtoMessage() {}

func (x *DownloadCRIBinariesSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadCRIBinariesSpec) GetContainerdVersion() string {
	if x != nil {
		if x.xxx_hidden_ContainerdVersion != nil {
			return *x.xxx_hidden_ContainerdVersion
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesSpec) GetRuncVersion() string {
	if x != nil {
		if x.xxx_hidden_RuncVersion != nil {
			return *x.xxx_hidden_RuncVersion
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesSpec) SetContainerdVersion(v string) {
	x.xxx_hidden_ContainerdVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DownloadCRIBinariesSpec) SetRuncVersion(v string) {
	x.xxx_hidden_RuncVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DownloadCRIBinariesSpec) HasContainerdVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadCRIBinariesSpec) HasRuncVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DownloadCRIBinariesSpec) ClearContainerdVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerdVersion = nil
}

func (x *DownloadCRIBinariesSpec) ClearRuncVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RuncVersion = nil
}

type DownloadCRIBinariesSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerdVersion *string
	RuncVersion       *string
}

func (b0 DownloadCRIBinariesSpec_builder) Build() *DownloadCRIBinariesSpec {
	m0 := &DownloadCRIBinariesSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerdVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ContainerdVersion = b.ContainerdVersion
	}
	if b.RuncVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_RuncVersion = b.RuncVersion
	}
	return m0
}

type DownloadCRIBinariesStatus struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerdDownloadUrl *string                `protobuf:"bytes,1,opt,name=containerd_download_url,json=containerdDownloadUrl"`
	xxx_hidden_ContainerdPath        *string                `protobuf:"bytes,2,opt,name=containerd_path,json=containerdPath"`
	xxx_hidden_RuncDownloadUrl       *string                `protobuf:"bytes,3,opt,name=runc_download_url,json=runcDownloadUrl"`
	xxx_hidden_RuncPath              *string                `protobuf:"bytes,4,opt,name=runc_path,json=runcPath"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *DownloadCRIBinariesStatus) Reset() {
	*x = DownloadCRIBinariesStatus{}
	mi := &file_components_cri_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadCRIBinariesStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadCRIBinariesStatus) ProtoMessage() {}

func (x *DownloadCRIBinariesStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadCRIBinariesStatus) GetContainerdDownloadUrl() string {
	if x != nil {
		if x.xxx_hidden_ContainerdDownloadUrl != nil {
			return *x.xxx_hidden_ContainerdDownloadUrl
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesStatus) GetContainerdPath() string {
	if x != nil {
		if x.xxx_hidden_ContainerdPath != nil {
			return *x.xxx_hidden_ContainerdPath
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesStatus) GetRuncDownloadUrl() string {
	if x != nil {
		if x.xxx_hidden_RuncDownloadUrl != nil {
			return *x.xxx_hidden_RuncDownloadUrl
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesStatus) GetRuncPath() string {
	if x != nil {
		if x.xxx_hidden_RuncPath != nil {
			return *x.xxx_hidden_RuncPath
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesStatus) SetContainerdDownloadUrl(v string) {
	x.xxx_hidden_ContainerdDownloadUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DownloadCRIBinariesStatus) SetContainerdPath(v string) {
	x.xxx_hidden_ContainerdPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DownloadCRIBinariesStatus) SetRuncDownloadUrl(v string) {
	x.xxx_hidden_RuncDownloadUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *DownloadCRIBinariesStatus) SetRuncPath(v string) {
	x.xxx_hidden_RuncPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *DownloadCRIBinariesStatus) HasContainerdDownloadUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadCRIBinariesStatus) HasContainerdPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DownloadCRIBinariesStatus) HasRuncDownloadUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DownloadCRIBinariesStatus) HasRuncPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DownloadCRIBinariesStatus) ClearContainerdDownloadUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerdDownloadUrl = nil
}

func (x *DownloadCRIBinariesStatus) ClearContainerdPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ContainerdPath = nil
}

func (x *DownloadCRIBinariesStatus) ClearRuncDownloadUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RuncDownloadUrl = nil
}

func (x *DownloadCRIBinariesStatus) ClearRuncPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_RuncPath = nil
}

type DownloadCRIBinariesStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerdDownloadUrl *string
	ContainerdPath        *string
	RuncDownloadUrl       *string
	RuncPath              *string
}

func (b0 DownloadCRIBinariesStatus_builder) Build() *DownloadCRIBinariesStatus {
	m0 := &DownloadCRIBinariesStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerdDownloadUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ContainerdDownloadUrl = b.ContainerdDownloadUrl
	}
	if b.ContainerdPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ContainerdPath = b.ContainerdPath
	}
	if b.RuncDownloadUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_RuncDownloadUrl = b.RuncDownloadUrl
	}
	if b.RuncPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_RuncPath = b.RuncPath
	}
	return m0
}

type StartContainerdService struct {
	state               protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata                 `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *StartContainerdServiceSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *StartContainerdServiceStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartContainerdService) Reset() {
	*x = StartContainerdService{}
	mi := &file_components_cri_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerdService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerdService) ProtoMessage() {}

func (x *StartContainerdService) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartContainerdService) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *StartContainerdService) GetSpec() *StartContainerdServiceSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *StartContainerdService) GetStatus() *StartContainerdServiceStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *StartContainerdService) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *StartContainerdService) SetSpec(v *StartContainerdServiceSpec) {
	x.xxx_hidden_Spec = v
}

func (x *StartContainerdService) SetStatus(v *StartContainerdServiceStatus) {
	x.xxx_hidden_Status = v
}

func (x *StartContainerdService) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *StartContainerdService) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *StartContainerdService) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *StartContainerdService) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *StartContainerdService) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *StartContainerdService) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type StartContainerdService_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *StartContainerdServiceSpec
	Status   *StartContainerdServiceStatus
}

func (b0 StartContainerdService_builder) Build() *StartContainerdService {
	m0 := &StartContainerdService{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type StartContainerdServiceSpec struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MetricsAddress *string                `protobuf:"bytes,1,opt,name=metrics_address,json=metricsAddress"`
	xxx_hidden_SandboxImage   *string                `protobuf:"bytes,2,opt,name=sandbox_image,json=sandboxImage"`
	xxx_hidden_CniConfig      *CNIConfig             `protobuf:"bytes,3,opt,name=cni_config,json=cniConfig"`
	xxx_hidden_GpuConfig      *GPUConfig             `protobuf:"bytes,4,opt,name=gpu_config,json=gpuConfig"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *StartContainerdServiceSpec) Reset() {
	*x = StartContainerdServiceSpec{}
	mi := &file_components_cri_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerdServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerdServiceSpec) ProtoMessage() {}

func (x *StartContainerdServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartContainerdServiceSpec) GetMetricsAddress() string {
	if x != nil {
		if x.xxx_hidden_MetricsAddress != nil {
			return *x.xxx_hidden_MetricsAddress
		}
		return ""
	}
	return ""
}

func (x *StartContainerdServiceSpec) GetSandboxImage() string {
	if x != nil {
		if x.xxx_hidden_SandboxImage != nil {
			return *x.xxx_hidden_SandboxImage
		}
		return ""
	}
	return ""
}

func (x *StartContainerdServiceSpec) GetCniConfig() *CNIConfig {
	if x != nil {
		return x.xxx_hidden_CniConfig
	}
	return nil
}

func (x *StartContainerdServiceSpec) GetGpuConfig() *GPUConfig {
	if x != nil {
		return x.xxx_hidden_GpuConfig
	}
	return nil
}

func (x *StartContainerdServiceSpec) SetMetricsAddress(v string) {
	x.xxx_hidden_MetricsAddress = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *StartContainerdServiceSpec) SetSandboxImage(v string) {
	x.xxx_hidden_SandboxImage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *StartContainerdServiceSpec) SetCniConfig(v *CNIConfig) {
	x.xxx_hidden_CniConfig = v
}

func (x *StartContainerdServiceSpec) SetGpuConfig(v *GPUConfig) {
	x.xxx_hidden_GpuConfig = v
}

func (x *StartContainerdServiceSpec) HasMetricsAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StartContainerdServiceSpec) HasSandboxImage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StartContainerdServiceSpec) HasCniConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CniConfig != nil
}

func (x *StartContainerdServiceSpec) HasGpuConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_GpuConfig != nil
}

func (x *StartContainerdServiceSpec) ClearMetricsAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MetricsAddress = nil
}

func (x *StartContainerdServiceSpec) ClearSandboxImage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SandboxImage = nil
}

func (x *StartContainerdServiceSpec) ClearCniConfig() {
	x.xxx_hidden_CniConfig = nil
}

func (x *StartContainerdServiceSpec) ClearGpuConfig() {
	x.xxx_hidden_GpuConfig = nil
}

type StartContainerdServiceSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Address for containerd metrics server to listen on, e.g. 0.0.0.0:10257"
	// Defaults to "0.0.0.0:10257". // FIXME: confirm why 0.0.0.0 is used instead of 127.0.0.1
	MetricsAddress *string
	// Image used for sandbox container.
	// Defaults to "mcr.microsoft.com/oss/containerd/pause:3.6".
	SandboxImage *string
	CniConfig    *CNIConfig
	GpuConfig    *GPUConfig
}

func (b0 StartContainerdServiceSpec_builder) Build() *StartContainerdServiceSpec {
	m0 := &StartContainerdServiceSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MetricsAddress != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_MetricsAddress = b.MetricsAddress
	}
	if b.SandboxImage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_SandboxImage = b.SandboxImage
	}
	x.xxx_hidden_CniConfig = b.CniConfig
	x.xxx_hidden_GpuConfig = b.GpuConfig
	return m0
}

// TODO: allow overriding cni config?
type CNIConfig struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BinDir      *string                `protobuf:"bytes,1,opt,name=bin_dir,json=binDir"`
	xxx_hidden_ConfigDir   *string                `protobuf:"bytes,2,opt,name=config_dir,json=configDir"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CNIConfig) Reset() {
	*x = CNIConfig{}
	mi := &file_components_cri_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CNIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNIConfig) ProtoMessage() {}

func (x *CNIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CNIConfig) GetBinDir() string {
	if x != nil {
		if x.xxx_hidden_BinDir != nil {
			return *x.xxx_hidden_BinDir
		}
		return ""
	}
	return ""
}

func (x *CNIConfig) GetConfigDir() string {
	if x != nil {
		if x.xxx_hidden_ConfigDir != nil {
			return *x.xxx_hidden_ConfigDir
		}
		return ""
	}
	return ""
}

func (x *CNIConfig) SetBinDir(v string) {
	x.xxx_hidden_BinDir = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CNIConfig) SetConfigDir(v string) {
	x.xxx_hidden_ConfigDir = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CNIConfig) HasBinDir() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CNIConfig) HasConfigDir() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CNIConfig) ClearBinDir() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BinDir = nil
}

func (x *CNIConfig) ClearConfigDir() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ConfigDir = nil
}

type CNIConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// CNI plugin directory
	// Defaults to "/opt/cni/bin"
	BinDir *string
	// CNI config directory
	// Defaults to "/etc/cni/net.d"
	ConfigDir *string
}

func (b0 CNIConfig_builder) Build() *CNIConfig {
	m0 := &CNIConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BinDir != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_BinDir = b.BinDir
	}
	if b.ConfigDir != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ConfigDir = b.ConfigDir
	}
	return m0
}

type GPUConfig struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GpuConfig isGPUConfig_GpuConfig  `protobuf_oneof:"gpu_config"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GPUConfig) Reset() {
	*x = GPUConfig{}
	mi := &file_components_cri_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUConfig) ProtoMessage() {}

func (x *GPUConfig) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GPUConfig) GetNvidiaRuntime() *NvidiaRuntime {
	if x != nil {
		if x, ok := x.xxx_hidden_GpuConfig.(*gPUConfig_NvidiaRuntime); ok {
			return x.NvidiaRuntime
		}
	}
	return nil
}

func (x *GPUConfig) SetNvidiaRuntime(v *NvidiaRuntime) {
	if v == nil {
		x.xxx_hidden_GpuConfig = nil
		return
	}
	x.xxx_hidden_GpuConfig = &gPUConfig_NvidiaRuntime{v}
}

func (x *GPUConfig) HasGpuConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_GpuConfig != nil
}

func (x *GPUConfig) HasNvidiaRuntime() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_GpuConfig.(*gPUConfig_NvidiaRuntime)
	return ok
}

func (x *GPUConfig) ClearGpuConfig() {
	x.xxx_hidden_GpuConfig = nil
}

func (x *GPUConfig) ClearNvidiaRuntime() {
	if _, ok := x.xxx_hidden_GpuConfig.(*gPUConfig_NvidiaRuntime); ok {
		x.xxx_hidden_GpuConfig = nil
	}
}

const GPUConfig_GpuConfig_not_set_case case_GPUConfig_GpuConfig = 0
const GPUConfig_NvidiaRuntime_case case_GPUConfig_GpuConfig = 1

func (x *GPUConfig) WhichGpuConfig() case_GPUConfig_GpuConfig {
	if x == nil {
		return GPUConfig_GpuConfig_not_set_case
	}
	switch x.xxx_hidden_GpuConfig.(type) {
	case *gPUConfig_NvidiaRuntime:
		return GPUConfig_NvidiaRuntime_case
	default:
		return GPUConfig_GpuConfig_not_set_case
	}
}

type GPUConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_GpuConfig:
	// enable GPU support via Nvidia Container Runtime
	NvidiaRuntime *NvidiaRuntime
	// -- end of xxx_hidden_GpuConfig
}

func (b0 GPUConfig_builder) Build() *GPUConfig {
	m0 := &GPUConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NvidiaRuntime != nil {
		x.xxx_hidden_GpuConfig = &gPUConfig_NvidiaRuntime{b.NvidiaRuntime}
	}
	return m0
}

type case_GPUConfig_GpuConfig protoreflect.FieldNumber

func (x case_GPUConfig_GpuConfig) String() string {
	md := file_components_cri_action_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isGPUConfig_GpuConfig interface {
	isGPUConfig_GpuConfig()
}

type gPUConfig_NvidiaRuntime struct {
	// enable GPU support via Nvidia Container Runtime
	NvidiaRuntime *NvidiaRuntime `protobuf:"bytes,1,opt,name=nvidia_runtime,json=nvidiaRuntime,oneof"`
}

func (*gPUConfig_NvidiaRuntime) isGPUConfig_GpuConfig() {}

type NvidiaRuntime struct {
	state                                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RuntimePath                *string                `protobuf:"bytes,1,opt,name=runtime_path,json=runtimePath"`
	xxx_hidden_RuntimeClassName           *string                `protobuf:"bytes,2,opt,name=runtime_class_name,json=runtimeClassName"`
	xxx_hidden_DisableSetAsDefaultRuntime bool                   `protobuf:"varint,3,opt,name=disable_set_as_default_runtime,json=disableSetAsDefaultRuntime"`
	XXX_raceDetectHookData                protoimpl.RaceDetectHookData
	XXX_presence                          [1]uint32
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *NvidiaRuntime) Reset() {
	*x = NvidiaRuntime{}
	mi := &file_components_cri_action_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NvidiaRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NvidiaRuntime) ProtoMessage() {}

func (x *NvidiaRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NvidiaRuntime) GetRuntimePath() string {
	if x != nil {
		if x.xxx_hidden_RuntimePath != nil {
			return *x.xxx_hidden_RuntimePath
		}
		return ""
	}
	return ""
}

func (x *NvidiaRuntime) GetRuntimeClassName() string {
	if x != nil {
		if x.xxx_hidden_RuntimeClassName != nil {
			return *x.xxx_hidden_RuntimeClassName
		}
		return ""
	}
	return ""
}

func (x *NvidiaRuntime) GetDisableSetAsDefaultRuntime() bool {
	if x != nil {
		return x.xxx_hidden_DisableSetAsDefaultRuntime
	}
	return false
}

func (x *NvidiaRuntime) SetRuntimePath(v string) {
	x.xxx_hidden_RuntimePath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *NvidiaRuntime) SetRuntimeClassName(v string) {
	x.xxx_hidden_RuntimeClassName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *NvidiaRuntime) SetDisableSetAsDefaultRuntime(v bool) {
	x.xxx_hidden_DisableSetAsDefaultRuntime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *NvidiaRuntime) HasRuntimePath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *NvidiaRuntime) HasRuntimeClassName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *NvidiaRuntime) HasDisableSetAsDefaultRuntime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *NvidiaRuntime) ClearRuntimePath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RuntimePath = nil
}

func (x *NvidiaRuntime) ClearRuntimeClassName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RuntimeClassName = nil
}

func (x *NvidiaRuntime) ClearDisableSetAsDefaultRuntime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_DisableSetAsDefaultRuntime = false
}

type NvidiaRuntime_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Absolute path to the nvidia-container-runtime binary.
	// Defaults to "/usr/bin/nvidia-container-runtime".
	RuntimePath *string
	// The runtime class name to use for GPU workloads.
	// Defaults to "nvidia".
	// NOTE: if disable_set_as_default_runtime is false, user is responsible
	// for ensuring the runtime class name object is being created in the cluster,
	// and the workload spec is configured to use the runtime class name,
	// otherwise GPU workload will fail to run.
	RuntimeClassName *string
	// Disable the behavior of settings nvidia-container-runtime as the
	// default runtime in containerd config.
	DisableSetAsDefaultRuntime *bool
}

func (b0 NvidiaRuntime_builder) Build() *NvidiaRuntime {
	m0 := &NvidiaRuntime{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RuntimePath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RuntimePath = b.RuntimePath
	}
	if b.RuntimeClassName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_RuntimeClassName = b.RuntimeClassName
	}
	if b.DisableSetAsDefaultRuntime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_DisableSetAsDefaultRuntime = *b.DisableSetAsDefaultRuntime
	}
	return m0
}

type StartContainerdServiceStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerdServiceStatus) Reset() {
	*x = StartContainerdServiceStatus{}
	mi := &file_components_cri_action_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerdServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerdServiceStatus) ProtoMessage() {}

func (x *StartContainerdServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StartContainerdServiceStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StartContainerdServiceStatus_builder) Build() *StartContainerdServiceStatus {
	m0 := &StartContainerdServiceStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ResetContainerdService struct {
	state               protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata                 `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *ResetContainerdServiceSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *ResetContainerdServiceStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResetContainerdService) Reset() {
	*x = ResetContainerdService{}
	mi := &file_components_cri_action_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetContainerdService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetContainerdService) ProtoMessage() {}

func (x *ResetContainerdService) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResetContainerdService) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ResetContainerdService) GetSpec() *ResetContainerdServiceSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *ResetContainerdService) GetStatus() *ResetContainerdServiceStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *ResetContainerdService) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ResetContainerdService) SetSpec(v *ResetContainerdServiceSpec) {
	x.xxx_hidden_Spec = v
}

func (x *ResetContainerdService) SetStatus(v *ResetContainerdServiceStatus) {
	x.xxx_hidden_Status = v
}

func (x *ResetContainerdService) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ResetContainerdService) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *ResetContainerdService) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *ResetContainerdService) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *ResetContainerdService) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *ResetContainerdService) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type ResetContainerdService_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *ResetContainerdServiceSpec
	Status   *ResetContainerdServiceStatus
}

func (b0 ResetContainerdService_builder) Build() *ResetContainerdService {
	m0 := &ResetContainerdService{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type ResetContainerdServiceSpec struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetContainerdServiceSpec) Reset() {
	*x = ResetContainerdServiceSpec{}
	mi := &file_components_cri_action_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetContainerdServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetContainerdServiceSpec) ProtoMessage() {}

func (x *ResetContainerdServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ResetContainerdServiceSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ResetContainerdServiceSpec_builder) Build() *ResetContainerdServiceSpec {
	m0 := &ResetContainerdServiceSpec{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ResetContainerdServiceStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetContainerdServiceStatus) Reset() {
	*x = ResetContainerdServiceStatus{}
	mi := &file_components_cri_action_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetContainerdServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetContainerdServiceStatus) ProtoMessage() {}

func (x *ResetContainerdServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_action_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ResetContainerdServiceStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ResetContainerdServiceStatus_builder) Build() *ResetContainerdServiceStatus {
	m0 := &ResetContainerdServiceStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_components_cri_action_proto protoreflect.FileDescriptor

const file_components_cri_action_proto_rawDesc = "" +
	"\n" +
	"\x1bcomponents/cri/action.proto\x12\x17aks.flex.components.cri\x1a\x18components/api/api.proto\"\xe6\x01\n" +
	"\x13DownloadCRIBinaries\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12D\n" +
	"\x04spec\x18\x02 \x01(\v20.aks.flex.components.cri.DownloadCRIBinariesSpecR\x04spec\x12J\n" +
	"\x06status\x18\x03 \x01(\v22.aks.flex.components.cri.DownloadCRIBinariesStatusR\x06status\"k\n" +
	"\x17DownloadCRIBinariesSpec\x12-\n" +
	"\x12containerd_version\x18\x01 \x01(\tR\x11containerdVersion\x12!\n" +
	"\frunc_version\x18\x02 \x01(\tR\vruncVersion\"\xc5\x01\n" +
	"\x19DownloadCRIBinariesStatus\x126\n" +
	"\x17containerd_download_url\x18\x01 \x01(\tR\x15containerdDownloadUrl\x12'\n" +
	"\x0fcontainerd_path\x18\x02 \x01(\tR\x0econtainerdPath\x12*\n" +
	"\x11runc_download_url\x18\x03 \x01(\tR\x0fruncDownloadUrl\x12\x1b\n" +
	"\trunc_path\x18\x04 \x01(\tR\bruncPath\"\xef\x01\n" +
	"\x16StartContainerdService\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12G\n" +
	"\x04spec\x18\x02 \x01(\v23.aks.flex.components.cri.StartContainerdServiceSpecR\x04spec\x12M\n" +
	"\x06status\x18\x03 \x01(\v25.aks.flex.components.cri.StartContainerdServiceStatusR\x06status\"\xf0\x01\n" +
	"\x1aStartContainerdServiceSpec\x12'\n" +
	"\x0fmetrics_address\x18\x01 \x01(\tR\x0emetricsAddress\x12#\n" +
	"\rsandbox_image\x18\x02 \x01(\tR\fsandboxImage\x12A\n" +
	"\n" +
	"cni_config\x18\x03 \x01(\v2\".aks.flex.components.cri.CNIConfigR\tcniConfig\x12A\n" +
	"\n" +
	"gpu_config\x18\x04 \x01(\v2\".aks.flex.components.cri.GPUConfigR\tgpuConfig\"C\n" +
	"\tCNIConfig\x12\x17\n" +
	"\abin_dir\x18\x01 \x01(\tR\x06binDir\x12\x1d\n" +
	"\n" +
	"config_dir\x18\x02 \x01(\tR\tconfigDir\"j\n" +
	"\tGPUConfig\x12O\n" +
	"\x0envidia_runtime\x18\x01 \x01(\v2&.aks.flex.components.cri.NvidiaRuntimeH\x00R\rnvidiaRuntimeB\f\n" +
	"\n" +
	"gpu_config\"\xa4\x01\n" +
	"\rNvidiaRuntime\x12!\n" +
	"\fruntime_path\x18\x01 \x01(\tR\vruntimePath\x12,\n" +
	"\x12runtime_class_name\x18\x02 \x01(\tR\x10runtimeClassName\x12B\n" +
	"\x1edisable_set_as_default_runtime\x18\x03 \x01(\bR\x1adisableSetAsDefaultRuntime\"\x1e\n" +
	"\x1cStartContainerdServiceStatus\"\xef\x01\n" +
	"\x16ResetContainerdService\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12G\n" +
	"\x04spec\x18\x02 \x01(\v23.aks.flex.components.cri.ResetContainerdServiceSpecR\x04spec\x12M\n" +
	"\x06status\x18\x03 \x01(\v25.aks.flex.components.cri.ResetContainerdServiceStatusR\x06status\"\x1c\n" +
	"\x1aResetContainerdServiceSpec\"\x1e\n" +
	"\x1cResetContainerdServiceStatusB-Z+github.com/Azure/AKSFlexNode/components/crib\beditionsp\xe9\a"

var file_components_cri_action_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_components_cri_action_proto_goTypes = []any{
	(*DownloadCRIBinaries)(nil),          // 0: aks.flex.components.cri.DownloadCRIBinaries
	(*DownloadCRIBinariesSpec)(nil),      // 1: aks.flex.components.cri.DownloadCRIBinariesSpec
	(*DownloadCRIBinariesStatus)(nil),    // 2: aks.flex.components.cri.DownloadCRIBinariesStatus
	(*StartContainerdService)(nil),       // 3: aks.flex.components.cri.StartContainerdService
	(*StartContainerdServiceSpec)(nil),   // 4: aks.flex.components.cri.StartContainerdServiceSpec
	(*CNIConfig)(nil),                    // 5: aks.flex.components.cri.CNIConfig
	(*GPUConfig)(nil),                    // 6: aks.flex.components.cri.GPUConfig
	(*NvidiaRuntime)(nil),                // 7: aks.flex.components.cri.NvidiaRuntime
	(*StartContainerdServiceStatus)(nil), // 8: aks.flex.components.cri.StartContainerdServiceStatus
	(*ResetContainerdService)(nil),       // 9: aks.flex.components.cri.ResetContainerdService
	(*ResetContainerdServiceSpec)(nil),   // 10: aks.flex.components.cri.ResetContainerdServiceSpec
	(*ResetContainerdServiceStatus)(nil), // 11: aks.flex.components.cri.ResetContainerdServiceStatus
	(*api.Metadata)(nil),                 // 12: aks.flex.components.api.Metadata
}
var file_components_cri_action_proto_depIdxs = []int32{
	12, // 0: aks.flex.components.cri.DownloadCRIBinaries.metadata:type_name -> aks.flex.components.api.Metadata
	1,  // 1: aks.flex.components.cri.DownloadCRIBinaries.spec:type_name -> aks.flex.components.cri.DownloadCRIBinariesSpec
	2,  // 2: aks.flex.components.cri.DownloadCRIBinaries.status:type_name -> aks.flex.components.cri.DownloadCRIBinariesStatus
	12, // 3: aks.flex.components.cri.StartContainerdService.metadata:type_name -> aks.flex.components.api.Metadata
	4,  // 4: aks.flex.components.cri.StartContainerdService.spec:type_name -> aks.flex.components.cri.StartContainerdServiceSpec
	8,  // 5: aks.flex.components.cri.StartContainerdService.status:type_name -> aks.flex.components.cri.StartContainerdServiceStatus
	5,  // 6: aks.flex.components.cri.StartContainerdServiceSpec.cni_config:type_name -> aks.flex.components.cri.CNIConfig
	6,  // 7: aks.flex.components.cri.StartContainerdServiceSpec.gpu_config:type_name -> aks.flex.components.cri.GPUConfig
	7,  // 8: aks.flex.components.cri.GPUConfig.nvidia_runtime:type_name -> aks.flex.components.cri.NvidiaRuntime
	12, // 9: aks.flex.components.cri.ResetContainerdService.metadata:type_name -> aks.flex.components.api.Metadata
	10, // 10: aks.flex.components.cri.ResetContainerdService.spec:type_name -> aks.flex.components.cri.ResetContainerdServiceSpec
	11, // 11: aks.flex.components.cri.ResetContainerdService.status:type_name -> aks.flex.components.cri.ResetContainerdServiceStatus
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_components_cri_action_proto_init() }
func file_components_cri_action_proto_init() {
	if File_components_cri_action_proto != nil {
		return
	}
	file_components_cri_action_proto_msgTypes[6].OneofWrappers = []any{
		(*gPUConfig_NvidiaRuntime)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_cri_action_proto_rawDesc), len(file_components_cri_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_cri_action_proto_goTypes,
		DependencyIndexes: file_components_cri_action_proto_depIdxs,
		MessageInfos:      file_components_cri_action_proto_msgTypes,
	}.Build()
	File_components_cri_action_proto = out.File
	file_components_cri_action_proto_goTypes = nil
	file_components_cri_action_proto_depIdxs = nil
}
