// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: components/npd/action.proto

package npd

import (
	reflect "reflect"
	unsafe "unsafe"

	api "github.com/Azure/AKSFlexNode/components/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadNodeProblemDetector struct {
	state               protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata                      `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *DownloadNodeProblemDetectorSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *DownloadNodeProblemDetectorStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DownloadNodeProblemDetector) Reset() {
	*x = DownloadNodeProblemDetector{}
	mi := &file_components_npd_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadNodeProblemDetector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadNodeProblemDetector) ProtoMessage() {}

func (x *DownloadNodeProblemDetector) ProtoReflect() protoreflect.Message {
	mi := &file_components_npd_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadNodeProblemDetector) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *DownloadNodeProblemDetector) GetSpec() *DownloadNodeProblemDetectorSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *DownloadNodeProblemDetector) GetStatus() *DownloadNodeProblemDetectorStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *DownloadNodeProblemDetector) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *DownloadNodeProblemDetector) SetSpec(v *DownloadNodeProblemDetectorSpec) {
	x.xxx_hidden_Spec = v
}

func (x *DownloadNodeProblemDetector) SetStatus(v *DownloadNodeProblemDetectorStatus) {
	x.xxx_hidden_Status = v
}

func (x *DownloadNodeProblemDetector) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *DownloadNodeProblemDetector) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *DownloadNodeProblemDetector) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *DownloadNodeProblemDetector) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *DownloadNodeProblemDetector) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *DownloadNodeProblemDetector) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type DownloadNodeProblemDetector_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *DownloadNodeProblemDetectorSpec
	Status   *DownloadNodeProblemDetectorStatus
}

func (b0 DownloadNodeProblemDetector_builder) Build() *DownloadNodeProblemDetector {
	m0 := &DownloadNodeProblemDetector{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type DownloadNodeProblemDetectorSpec struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version     *string                `protobuf:"bytes,1,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DownloadNodeProblemDetectorSpec) Reset() {
	*x = DownloadNodeProblemDetectorSpec{}
	mi := &file_components_npd_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadNodeProblemDetectorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadNodeProblemDetectorSpec) ProtoMessage() {}

func (x *DownloadNodeProblemDetectorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_npd_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadNodeProblemDetectorSpec) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *DownloadNodeProblemDetectorSpec) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DownloadNodeProblemDetectorSpec) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadNodeProblemDetectorSpec) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Version = nil
}

type DownloadNodeProblemDetectorSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// NPD version to download.
	// Defaults to v1.35.1 if not specified.
	Version *string
}

func (b0 DownloadNodeProblemDetectorSpec_builder) Build() *DownloadNodeProblemDetectorSpec {
	m0 := &DownloadNodeProblemDetectorSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Version = b.Version
	}
	return m0
}

type DownloadNodeProblemDetectorStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DownloadUrl *string                `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl"`
	xxx_hidden_BinaryPath  *string                `protobuf:"bytes,2,opt,name=binary_path,json=binaryPath"`
	xxx_hidden_ConfigPath  *string                `protobuf:"bytes,3,opt,name=config_path,json=configPath"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DownloadNodeProblemDetectorStatus) Reset() {
	*x = DownloadNodeProblemDetectorStatus{}
	mi := &file_components_npd_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadNodeProblemDetectorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadNodeProblemDetectorStatus) ProtoMessage() {}

func (x *DownloadNodeProblemDetectorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_npd_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadNodeProblemDetectorStatus) GetDownloadUrl() string {
	if x != nil {
		if x.xxx_hidden_DownloadUrl != nil {
			return *x.xxx_hidden_DownloadUrl
		}
		return ""
	}
	return ""
}

func (x *DownloadNodeProblemDetectorStatus) GetBinaryPath() string {
	if x != nil {
		if x.xxx_hidden_BinaryPath != nil {
			return *x.xxx_hidden_BinaryPath
		}
		return ""
	}
	return ""
}

func (x *DownloadNodeProblemDetectorStatus) GetConfigPath() string {
	if x != nil {
		if x.xxx_hidden_ConfigPath != nil {
			return *x.xxx_hidden_ConfigPath
		}
		return ""
	}
	return ""
}

func (x *DownloadNodeProblemDetectorStatus) SetDownloadUrl(v string) {
	x.xxx_hidden_DownloadUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *DownloadNodeProblemDetectorStatus) SetBinaryPath(v string) {
	x.xxx_hidden_BinaryPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *DownloadNodeProblemDetectorStatus) SetConfigPath(v string) {
	x.xxx_hidden_ConfigPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *DownloadNodeProblemDetectorStatus) HasDownloadUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadNodeProblemDetectorStatus) HasBinaryPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DownloadNodeProblemDetectorStatus) HasConfigPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DownloadNodeProblemDetectorStatus) ClearDownloadUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DownloadUrl = nil
}

func (x *DownloadNodeProblemDetectorStatus) ClearBinaryPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_BinaryPath = nil
}

func (x *DownloadNodeProblemDetectorStatus) ClearConfigPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ConfigPath = nil
}

type DownloadNodeProblemDetectorStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// URL to download the NPD binary.
	DownloadUrl *string
	// Path to the downloaded NPD binary on the node.
	BinaryPath *string
	// Path to the NPD configuration file on the node.
	ConfigPath *string
}

func (b0 DownloadNodeProblemDetectorStatus_builder) Build() *DownloadNodeProblemDetectorStatus {
	m0 := &DownloadNodeProblemDetectorStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DownloadUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_DownloadUrl = b.DownloadUrl
	}
	if b.BinaryPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_BinaryPath = b.BinaryPath
	}
	if b.ConfigPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ConfigPath = b.ConfigPath
	}
	return m0
}

type StartNodeProblemDetector struct {
	state               protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata                   `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *StartNodeProblemDetectorSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *StartNodeProblemDetectorStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartNodeProblemDetector) Reset() {
	*x = StartNodeProblemDetector{}
	mi := &file_components_npd_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartNodeProblemDetector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNodeProblemDetector) ProtoMessage() {}

func (x *StartNodeProblemDetector) ProtoReflect() protoreflect.Message {
	mi := &file_components_npd_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartNodeProblemDetector) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *StartNodeProblemDetector) GetSpec() *StartNodeProblemDetectorSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *StartNodeProblemDetector) GetStatus() *StartNodeProblemDetectorStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *StartNodeProblemDetector) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *StartNodeProblemDetector) SetSpec(v *StartNodeProblemDetectorSpec) {
	x.xxx_hidden_Spec = v
}

func (x *StartNodeProblemDetector) SetStatus(v *StartNodeProblemDetectorStatus) {
	x.xxx_hidden_Status = v
}

func (x *StartNodeProblemDetector) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *StartNodeProblemDetector) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *StartNodeProblemDetector) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *StartNodeProblemDetector) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *StartNodeProblemDetector) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *StartNodeProblemDetector) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type StartNodeProblemDetector_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *StartNodeProblemDetectorSpec
	Status   *StartNodeProblemDetectorStatus
}

func (b0 StartNodeProblemDetector_builder) Build() *StartNodeProblemDetector {
	m0 := &StartNodeProblemDetector{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type StartNodeProblemDetectorSpec struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ApiServer      *string                `protobuf:"bytes,1,opt,name=api_server,json=apiServer"`
	xxx_hidden_KubeConfigPath *string                `protobuf:"bytes,2,opt,name=kube_config_path,json=kubeConfigPath"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *StartNodeProblemDetectorSpec) Reset() {
	*x = StartNodeProblemDetectorSpec{}
	mi := &file_components_npd_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartNodeProblemDetectorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNodeProblemDetectorSpec) ProtoMessage() {}

func (x *StartNodeProblemDetectorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_npd_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartNodeProblemDetectorSpec) GetApiServer() string {
	if x != nil {
		if x.xxx_hidden_ApiServer != nil {
			return *x.xxx_hidden_ApiServer
		}
		return ""
	}
	return ""
}

func (x *StartNodeProblemDetectorSpec) GetKubeConfigPath() string {
	if x != nil {
		if x.xxx_hidden_KubeConfigPath != nil {
			return *x.xxx_hidden_KubeConfigPath
		}
		return ""
	}
	return ""
}

func (x *StartNodeProblemDetectorSpec) SetApiServer(v string) {
	x.xxx_hidden_ApiServer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StartNodeProblemDetectorSpec) SetKubeConfigPath(v string) {
	x.xxx_hidden_KubeConfigPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StartNodeProblemDetectorSpec) HasApiServer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StartNodeProblemDetectorSpec) HasKubeConfigPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StartNodeProblemDetectorSpec) ClearApiServer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ApiServer = nil
}

func (x *StartNodeProblemDetectorSpec) ClearKubeConfigPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_KubeConfigPath = nil
}

type StartNodeProblemDetectorSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// API server address for NPD to connect to.
	ApiServer *string
	// Path to the kubeconfig file for NPD to connect to the API server.
	KubeConfigPath *string
}

func (b0 StartNodeProblemDetectorSpec_builder) Build() *StartNodeProblemDetectorSpec {
	m0 := &StartNodeProblemDetectorSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ApiServer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ApiServer = b.ApiServer
	}
	if b.KubeConfigPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_KubeConfigPath = b.KubeConfigPath
	}
	return m0
}

type StartNodeProblemDetectorStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartNodeProblemDetectorStatus) Reset() {
	*x = StartNodeProblemDetectorStatus{}
	mi := &file_components_npd_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartNodeProblemDetectorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNodeProblemDetectorStatus) ProtoMessage() {}

func (x *StartNodeProblemDetectorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_npd_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StartNodeProblemDetectorStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StartNodeProblemDetectorStatus_builder) Build() *StartNodeProblemDetectorStatus {
	m0 := &StartNodeProblemDetectorStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_components_npd_action_proto protoreflect.FileDescriptor

const file_components_npd_action_proto_rawDesc = "" +
	"\n" +
	"\x1bcomponents/npd/action.proto\x12\x17aks.flex.components.npd\x1a\x18components/api/api.proto\"\xfe\x01\n" +
	"\x1bDownloadNodeProblemDetector\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12L\n" +
	"\x04spec\x18\x02 \x01(\v28.aks.flex.components.npd.DownloadNodeProblemDetectorSpecR\x04spec\x12R\n" +
	"\x06status\x18\x03 \x01(\v2:.aks.flex.components.npd.DownloadNodeProblemDetectorStatusR\x06status\";\n" +
	"\x1fDownloadNodeProblemDetectorSpec\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x88\x01\n" +
	"!DownloadNodeProblemDetectorStatus\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12\x1f\n" +
	"\vbinary_path\x18\x02 \x01(\tR\n" +
	"binaryPath\x12\x1f\n" +
	"\vconfig_path\x18\x03 \x01(\tR\n" +
	"configPath\"\xf5\x01\n" +
	"\x18StartNodeProblemDetector\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12I\n" +
	"\x04spec\x18\x02 \x01(\v25.aks.flex.components.npd.StartNodeProblemDetectorSpecR\x04spec\x12O\n" +
	"\x06status\x18\x03 \x01(\v27.aks.flex.components.npd.StartNodeProblemDetectorStatusR\x06status\"g\n" +
	"\x1cStartNodeProblemDetectorSpec\x12\x1d\n" +
	"\n" +
	"api_server\x18\x01 \x01(\tR\tapiServer\x12(\n" +
	"\x10kube_config_path\x18\x02 \x01(\tR\x0ekubeConfigPath\" \n" +
	"\x1eStartNodeProblemDetectorStatusB-Z+github.com/Azure/AKSFlexNode/components/npdb\beditionsp\xe9\a"

var file_components_npd_action_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_components_npd_action_proto_goTypes = []any{
	(*DownloadNodeProblemDetector)(nil),       // 0: aks.flex.components.npd.DownloadNodeProblemDetector
	(*DownloadNodeProblemDetectorSpec)(nil),   // 1: aks.flex.components.npd.DownloadNodeProblemDetectorSpec
	(*DownloadNodeProblemDetectorStatus)(nil), // 2: aks.flex.components.npd.DownloadNodeProblemDetectorStatus
	(*StartNodeProblemDetector)(nil),          // 3: aks.flex.components.npd.StartNodeProblemDetector
	(*StartNodeProblemDetectorSpec)(nil),      // 4: aks.flex.components.npd.StartNodeProblemDetectorSpec
	(*StartNodeProblemDetectorStatus)(nil),    // 5: aks.flex.components.npd.StartNodeProblemDetectorStatus
	(*api.Metadata)(nil),                      // 6: aks.flex.components.api.Metadata
}
var file_components_npd_action_proto_depIdxs = []int32{
	6, // 0: aks.flex.components.npd.DownloadNodeProblemDetector.metadata:type_name -> aks.flex.components.api.Metadata
	1, // 1: aks.flex.components.npd.DownloadNodeProblemDetector.spec:type_name -> aks.flex.components.npd.DownloadNodeProblemDetectorSpec
	2, // 2: aks.flex.components.npd.DownloadNodeProblemDetector.status:type_name -> aks.flex.components.npd.DownloadNodeProblemDetectorStatus
	6, // 3: aks.flex.components.npd.StartNodeProblemDetector.metadata:type_name -> aks.flex.components.api.Metadata
	4, // 4: aks.flex.components.npd.StartNodeProblemDetector.spec:type_name -> aks.flex.components.npd.StartNodeProblemDetectorSpec
	5, // 5: aks.flex.components.npd.StartNodeProblemDetector.status:type_name -> aks.flex.components.npd.StartNodeProblemDetectorStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_components_npd_action_proto_init() }
func file_components_npd_action_proto_init() {
	if File_components_npd_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_npd_action_proto_rawDesc), len(file_components_npd_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_npd_action_proto_goTypes,
		DependencyIndexes: file_components_npd_action_proto_depIdxs,
		MessageInfos:      file_components_npd_action_proto_msgTypes,
	}.Build()
	File_components_npd_action_proto = out.File
	file_components_npd_action_proto_goTypes = nil
	file_components_npd_action_proto_depIdxs = nil
}
