// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: components/kubebins/action.proto

package kubebins

import (
	api "github.com/Azure/AKSFlexNode/components/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadKubeBinaries struct {
	state               protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata               `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *DownloadKubeBinariesSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *DownloadKubeBinariesStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DownloadKubeBinaries) Reset() {
	*x = DownloadKubeBinaries{}
	mi := &file_components_kubebins_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadKubeBinaries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadKubeBinaries) ProtoMessage() {}

func (x *DownloadKubeBinaries) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubebins_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadKubeBinaries) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *DownloadKubeBinaries) GetSpec() *DownloadKubeBinariesSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *DownloadKubeBinaries) GetStatus() *DownloadKubeBinariesStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *DownloadKubeBinaries) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *DownloadKubeBinaries) SetSpec(v *DownloadKubeBinariesSpec) {
	x.xxx_hidden_Spec = v
}

func (x *DownloadKubeBinaries) SetStatus(v *DownloadKubeBinariesStatus) {
	x.xxx_hidden_Status = v
}

func (x *DownloadKubeBinaries) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *DownloadKubeBinaries) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *DownloadKubeBinaries) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *DownloadKubeBinaries) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *DownloadKubeBinaries) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *DownloadKubeBinaries) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type DownloadKubeBinaries_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *DownloadKubeBinariesSpec
	Status   *DownloadKubeBinariesStatus
}

func (b0 DownloadKubeBinaries_builder) Build() *DownloadKubeBinaries {
	m0 := &DownloadKubeBinaries{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type DownloadKubeBinariesSpec struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_KubernetesVersion *string                `protobuf:"bytes,1,opt,name=kubernetes_version,json=kubernetesVersion"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DownloadKubeBinariesSpec) Reset() {
	*x = DownloadKubeBinariesSpec{}
	mi := &file_components_kubebins_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadKubeBinariesSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadKubeBinariesSpec) ProtoMessage() {}

func (x *DownloadKubeBinariesSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubebins_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadKubeBinariesSpec) GetKubernetesVersion() string {
	if x != nil {
		if x.xxx_hidden_KubernetesVersion != nil {
			return *x.xxx_hidden_KubernetesVersion
		}
		return ""
	}
	return ""
}

func (x *DownloadKubeBinariesSpec) SetKubernetesVersion(v string) {
	x.xxx_hidden_KubernetesVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DownloadKubeBinariesSpec) HasKubernetesVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadKubeBinariesSpec) ClearKubernetesVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_KubernetesVersion = nil
}

type DownloadKubeBinariesSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	KubernetesVersion *string
}

func (b0 DownloadKubeBinariesSpec_builder) Build() *DownloadKubeBinariesSpec {
	m0 := &DownloadKubeBinariesSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.KubernetesVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_KubernetesVersion = b.KubernetesVersion
	}
	return m0
}

type DownloadKubeBinariesStatus struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DownloadUrl          *string                `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl"`
	xxx_hidden_KubeletPath          *string                `protobuf:"bytes,2,opt,name=kubelet_path,json=kubeletPath"`
	xxx_hidden_KubeadmPath          *string                `protobuf:"bytes,3,opt,name=kubeadm_path,json=kubeadmPath"`
	xxx_hidden_KubectlPath          *string                `protobuf:"bytes,4,opt,name=kubectl_path,json=kubectlPath"`
	xxx_hidden_KubeProxyPath        *string                `protobuf:"bytes,5,opt,name=kube_proxy_path,json=kubeProxyPath"`
	xxx_hidden_KubeletDownloadUrl   *string                `protobuf:"bytes,6,opt,name=kubelet_download_url,json=kubeletDownloadUrl"`
	xxx_hidden_KubeadmDownloadUrl   *string                `protobuf:"bytes,7,opt,name=kubeadm_download_url,json=kubeadmDownloadUrl"`
	xxx_hidden_KubectlDownloadUrl   *string                `protobuf:"bytes,8,opt,name=kubectl_download_url,json=kubectlDownloadUrl"`
	xxx_hidden_KubeProxyDownloadUrl *string                `protobuf:"bytes,9,opt,name=kube_proxy_download_url,json=kubeProxyDownloadUrl"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *DownloadKubeBinariesStatus) Reset() {
	*x = DownloadKubeBinariesStatus{}
	mi := &file_components_kubebins_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadKubeBinariesStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadKubeBinariesStatus) ProtoMessage() {}

func (x *DownloadKubeBinariesStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_kubebins_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Marked as deprecated in components/kubebins/action.proto.
func (x *DownloadKubeBinariesStatus) GetDownloadUrl() string {
	if x != nil {
		if x.xxx_hidden_DownloadUrl != nil {
			return *x.xxx_hidden_DownloadUrl
		}
		return ""
	}
	return ""
}

func (x *DownloadKubeBinariesStatus) GetKubeletPath() string {
	if x != nil {
		if x.xxx_hidden_KubeletPath != nil {
			return *x.xxx_hidden_KubeletPath
		}
		return ""
	}
	return ""
}

func (x *DownloadKubeBinariesStatus) GetKubeadmPath() string {
	if x != nil {
		if x.xxx_hidden_KubeadmPath != nil {
			return *x.xxx_hidden_KubeadmPath
		}
		return ""
	}
	return ""
}

func (x *DownloadKubeBinariesStatus) GetKubectlPath() string {
	if x != nil {
		if x.xxx_hidden_KubectlPath != nil {
			return *x.xxx_hidden_KubectlPath
		}
		return ""
	}
	return ""
}

func (x *DownloadKubeBinariesStatus) GetKubeProxyPath() string {
	if x != nil {
		if x.xxx_hidden_KubeProxyPath != nil {
			return *x.xxx_hidden_KubeProxyPath
		}
		return ""
	}
	return ""
}

func (x *DownloadKubeBinariesStatus) GetKubeletDownloadUrl() string {
	if x != nil {
		if x.xxx_hidden_KubeletDownloadUrl != nil {
			return *x.xxx_hidden_KubeletDownloadUrl
		}
		return ""
	}
	return ""
}

func (x *DownloadKubeBinariesStatus) GetKubeadmDownloadUrl() string {
	if x != nil {
		if x.xxx_hidden_KubeadmDownloadUrl != nil {
			return *x.xxx_hidden_KubeadmDownloadUrl
		}
		return ""
	}
	return ""
}

func (x *DownloadKubeBinariesStatus) GetKubectlDownloadUrl() string {
	if x != nil {
		if x.xxx_hidden_KubectlDownloadUrl != nil {
			return *x.xxx_hidden_KubectlDownloadUrl
		}
		return ""
	}
	return ""
}

func (x *DownloadKubeBinariesStatus) GetKubeProxyDownloadUrl() string {
	if x != nil {
		if x.xxx_hidden_KubeProxyDownloadUrl != nil {
			return *x.xxx_hidden_KubeProxyDownloadUrl
		}
		return ""
	}
	return ""
}

// Deprecated: Marked as deprecated in components/kubebins/action.proto.
func (x *DownloadKubeBinariesStatus) SetDownloadUrl(v string) {
	x.xxx_hidden_DownloadUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *DownloadKubeBinariesStatus) SetKubeletPath(v string) {
	x.xxx_hidden_KubeletPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *DownloadKubeBinariesStatus) SetKubeadmPath(v string) {
	x.xxx_hidden_KubeadmPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *DownloadKubeBinariesStatus) SetKubectlPath(v string) {
	x.xxx_hidden_KubectlPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *DownloadKubeBinariesStatus) SetKubeProxyPath(v string) {
	x.xxx_hidden_KubeProxyPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *DownloadKubeBinariesStatus) SetKubeletDownloadUrl(v string) {
	x.xxx_hidden_KubeletDownloadUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *DownloadKubeBinariesStatus) SetKubeadmDownloadUrl(v string) {
	x.xxx_hidden_KubeadmDownloadUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *DownloadKubeBinariesStatus) SetKubectlDownloadUrl(v string) {
	x.xxx_hidden_KubectlDownloadUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *DownloadKubeBinariesStatus) SetKubeProxyDownloadUrl(v string) {
	x.xxx_hidden_KubeProxyDownloadUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

// Deprecated: Marked as deprecated in components/kubebins/action.proto.
func (x *DownloadKubeBinariesStatus) HasDownloadUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadKubeBinariesStatus) HasKubeletPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DownloadKubeBinariesStatus) HasKubeadmPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DownloadKubeBinariesStatus) HasKubectlPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DownloadKubeBinariesStatus) HasKubeProxyPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *DownloadKubeBinariesStatus) HasKubeletDownloadUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *DownloadKubeBinariesStatus) HasKubeadmDownloadUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *DownloadKubeBinariesStatus) HasKubectlDownloadUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *DownloadKubeBinariesStatus) HasKubeProxyDownloadUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

// Deprecated: Marked as deprecated in components/kubebins/action.proto.
func (x *DownloadKubeBinariesStatus) ClearDownloadUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DownloadUrl = nil
}

func (x *DownloadKubeBinariesStatus) ClearKubeletPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_KubeletPath = nil
}

func (x *DownloadKubeBinariesStatus) ClearKubeadmPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_KubeadmPath = nil
}

func (x *DownloadKubeBinariesStatus) ClearKubectlPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_KubectlPath = nil
}

func (x *DownloadKubeBinariesStatus) ClearKubeProxyPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_KubeProxyPath = nil
}

func (x *DownloadKubeBinariesStatus) ClearKubeletDownloadUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_KubeletDownloadUrl = nil
}

func (x *DownloadKubeBinariesStatus) ClearKubeadmDownloadUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_KubeadmDownloadUrl = nil
}

func (x *DownloadKubeBinariesStatus) ClearKubectlDownloadUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_KubectlDownloadUrl = nil
}

func (x *DownloadKubeBinariesStatus) ClearKubeProxyDownloadUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_KubeProxyDownloadUrl = nil
}

type DownloadKubeBinariesStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Deprecated: Marked as deprecated in components/kubebins/action.proto.
	DownloadUrl          *string
	KubeletPath          *string
	KubeadmPath          *string
	KubectlPath          *string
	KubeProxyPath        *string
	KubeletDownloadUrl   *string
	KubeadmDownloadUrl   *string
	KubectlDownloadUrl   *string
	KubeProxyDownloadUrl *string
}

func (b0 DownloadKubeBinariesStatus_builder) Build() *DownloadKubeBinariesStatus {
	m0 := &DownloadKubeBinariesStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DownloadUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_DownloadUrl = b.DownloadUrl
	}
	if b.KubeletPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_KubeletPath = b.KubeletPath
	}
	if b.KubeadmPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_KubeadmPath = b.KubeadmPath
	}
	if b.KubectlPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_KubectlPath = b.KubectlPath
	}
	if b.KubeProxyPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_KubeProxyPath = b.KubeProxyPath
	}
	if b.KubeletDownloadUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_KubeletDownloadUrl = b.KubeletDownloadUrl
	}
	if b.KubeadmDownloadUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_KubeadmDownloadUrl = b.KubeadmDownloadUrl
	}
	if b.KubectlDownloadUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_KubectlDownloadUrl = b.KubectlDownloadUrl
	}
	if b.KubeProxyDownloadUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_KubeProxyDownloadUrl = b.KubeProxyDownloadUrl
	}
	return m0
}

var File_components_kubebins_action_proto protoreflect.FileDescriptor

const file_components_kubebins_action_proto_rawDesc = "" +
	"\n" +
	" components/kubebins/action.proto\x12\x1caks.flex.components.kubebins\x1a\x18components/api/api.proto\"\xf3\x01\n" +
	"\x14DownloadKubeBinaries\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12J\n" +
	"\x04spec\x18\x02 \x01(\v26.aks.flex.components.kubebins.DownloadKubeBinariesSpecR\x04spec\x12P\n" +
	"\x06status\x18\x03 \x01(\v28.aks.flex.components.kubebins.DownloadKubeBinariesStatusR\x06status\"I\n" +
	"\x18DownloadKubeBinariesSpec\x12-\n" +
	"\x12kubernetes_version\x18\x01 \x01(\tR\x11kubernetesVersion\"\xa1\x03\n" +
	"\x1aDownloadKubeBinariesStatus\x12%\n" +
	"\fdownload_url\x18\x01 \x01(\tB\x02\x18\x01R\vdownloadUrl\x12!\n" +
	"\fkubelet_path\x18\x02 \x01(\tR\vkubeletPath\x12!\n" +
	"\fkubeadm_path\x18\x03 \x01(\tR\vkubeadmPath\x12!\n" +
	"\fkubectl_path\x18\x04 \x01(\tR\vkubectlPath\x12&\n" +
	"\x0fkube_proxy_path\x18\x05 \x01(\tR\rkubeProxyPath\x120\n" +
	"\x14kubelet_download_url\x18\x06 \x01(\tR\x12kubeletDownloadUrl\x120\n" +
	"\x14kubeadm_download_url\x18\a \x01(\tR\x12kubeadmDownloadUrl\x120\n" +
	"\x14kubectl_download_url\x18\b \x01(\tR\x12kubectlDownloadUrl\x125\n" +
	"\x17kube_proxy_download_url\x18\t \x01(\tR\x14kubeProxyDownloadUrlB2Z0github.com/Azure/AKSFlexNode/components/kubebinsb\beditionsp\xe9\a"

var file_components_kubebins_action_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_components_kubebins_action_proto_goTypes = []any{
	(*DownloadKubeBinaries)(nil),       // 0: aks.flex.components.kubebins.DownloadKubeBinaries
	(*DownloadKubeBinariesSpec)(nil),   // 1: aks.flex.components.kubebins.DownloadKubeBinariesSpec
	(*DownloadKubeBinariesStatus)(nil), // 2: aks.flex.components.kubebins.DownloadKubeBinariesStatus
	(*api.Metadata)(nil),               // 3: aks.flex.components.api.Metadata
}
var file_components_kubebins_action_proto_depIdxs = []int32{
	3, // 0: aks.flex.components.kubebins.DownloadKubeBinaries.metadata:type_name -> aks.flex.components.api.Metadata
	1, // 1: aks.flex.components.kubebins.DownloadKubeBinaries.spec:type_name -> aks.flex.components.kubebins.DownloadKubeBinariesSpec
	2, // 2: aks.flex.components.kubebins.DownloadKubeBinaries.status:type_name -> aks.flex.components.kubebins.DownloadKubeBinariesStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_kubebins_action_proto_init() }
func file_components_kubebins_action_proto_init() {
	if File_components_kubebins_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_kubebins_action_proto_rawDesc), len(file_components_kubebins_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_kubebins_action_proto_goTypes,
		DependencyIndexes: file_components_kubebins_action_proto_depIdxs,
		MessageInfos:      file_components_kubebins_action_proto_msgTypes,
	}.Build()
	File_components_kubebins_action_proto = out.File
	file_components_kubebins_action_proto_goTypes = nil
	file_components_kubebins_action_proto_depIdxs = nil
}
